-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object exposing (..)


type Account
    = Account


type AccountsPaginated
    = AccountsPaginated


type Admissibility
    = Admissibility


type AdmissibilityFvae
    = AdmissibilityFvae


type BasicSkill
    = BasicSkill


type BlocCompetence
    = BlocCompetence


type Candidacy
    = Candidacy


type CandidacyConventionCollective
    = CandidacyConventionCollective


type CandidacyConventionCollectivePaginated
    = CandidacyConventionCollectivePaginated


type CandidacyCountByStatus
    = CandidacyCountByStatus


type CandidacyDropOut
    = CandidacyDropOut


type CandidacyLog
    = CandidacyLog


type CandidacyLogUser
    = CandidacyLogUser


type CandidacyMenu
    = CandidacyMenu


type CandidacyMenuEntry
    = CandidacyMenuEntry


type CandidacyStatus
    = CandidacyStatus


type CandidacySummary
    = CandidacySummary


type CandidacySummaryFilterInfo
    = CandidacySummaryFilterInfo


type CandidacySummaryPage
    = CandidacySummaryPage


type Candidate
    = Candidate


type CandidateLogged
    = CandidateLogged


type Certification
    = Certification


type CertificationAuhtorityOrLocalAccountPaginated
    = CertificationAuhtorityOrLocalAccountPaginated


type CertificationAuthority
    = CertificationAuthority


type CertificationAuthorityLocalAccount
    = CertificationAuthorityLocalAccount


type CertificationAuthorityOrLocalAccount
    = CertificationAuthorityOrLocalAccount


type CertificationAuthorityPaginated
    = CertificationAuthorityPaginated


type CertificationCompetence
    = CertificationCompetence


type CertificationCompetenceBloc
    = CertificationCompetenceBloc


type CertificationCompetenceDetails
    = CertificationCompetenceDetails


type CertificationPage
    = CertificationPage


type CertificationSummary
    = CertificationSummary


type ConventionCollective
    = ConventionCollective


type Country
    = Country


type DFFAttachment
    = DFFAttachment


type DFFCertificationCompetenceBloc
    = DFFCertificationCompetenceBloc


type Degree
    = Degree


type DematerializedFeasibilityFile
    = DematerializedFeasibilityFile


type Department
    = Department


type Domaine
    = Domaine


type DossierDeValidation
    = DossierDeValidation


type DossierDeValidationCountByCategory
    = DossierDeValidationCountByCategory


type DossierDeValidationPage
    = DossierDeValidationPage


type DropOutReason
    = DropOutReason


type Etablissement
    = Etablissement


type EtablissementDiffusible
    = EtablissementDiffusible


type ExamInfo
    = ExamInfo


type Experience
    = Experience


type FCCertification
    = FCCertification


type Feasibility
    = Feasibility


type FeasibilityCountByCategory
    = FeasibilityCountByCategory


type FeasibilityHistory
    = FeasibilityHistory


type FeasibilityPage
    = FeasibilityPage


type Feature
    = Feature


type File
    = File


type FormeJuridique
    = FormeJuridique


type FundingRequest
    = FundingRequest


type FundingRequestInformations
    = FundingRequestInformations


type FundingRequestUnifvae
    = FundingRequestUnifvae


type Goal
    = Goal


type Jury
    = Jury


type JuryCountByCategory
    = JuryCountByCategory


type JuryPage
    = JuryPage


type Kbis
    = Kbis


type MaisonMereAAP
    = MaisonMereAAP


type MaisonMereAAPCGU
    = MaisonMereAAPCGU


type MaisonMereAAPLegalInformationDocuments
    = MaisonMereAAPLegalInformationDocuments


type MaisonMereAAPLegalInformationDocumentsDecision
    = MaisonMereAAPLegalInformationDocumentsDecision


type MaisonMereAAPOnConventionCollective
    = MaisonMereAAPOnConventionCollective


type MaisonMereAAPOnDepartment
    = MaisonMereAAPOnDepartment


type MaisonMereAAPsPaginated
    = MaisonMereAAPsPaginated


type MandataireSocial
    = MandataireSocial


type Organism
    = Organism


type OrganismInformationsCommerciales
    = OrganismInformationsCommerciales


type OrganismOnDegree
    = OrganismOnDegree


type OrganismOnDepartment
    = OrganismOnDepartment


type PaginationInfo
    = PaginationInfo


type PaymentRequest
    = PaymentRequest


type PaymentRequestUnifvae
    = PaymentRequestUnifvae


type Prerequisite
    = Prerequisite


type RamdomOrganisms
    = RamdomOrganisms


type Referential
    = Referential


type Region
    = Region


type ReorientationReason
    = ReorientationReason


type SubscriptionCountByStatus
    = SubscriptionCountByStatus


type SubscriptionRequest
    = SubscriptionRequest


type SubscriptionRequestsPaginated
    = SubscriptionRequestsPaginated


type Tokens
    = Tokens


type Training
    = Training


type TrainingForm
    = TrainingForm


type TypeDiplome
    = TypeDiplome


type VulnerabilityIndicator
    = VulnerabilityIndicator
