-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object exposing (..)


type Account
    = Account


type AccountsPaginated
    = AccountsPaginated


type Admissibility
    = Admissibility


type BasicSkill
    = BasicSkill


type Candidacy
    = Candidacy


type CandidacyCountByStatus
    = CandidacyCountByStatus


type CandidacyDropOut
    = CandidacyDropOut


type CandidacyStatus
    = CandidacyStatus


type CandidacySummary
    = CandidacySummary


type CandidacySummaryFilterInfo
    = CandidacySummaryFilterInfo


type CandidacySummaryPage
    = CandidacySummaryPage


type Candidate
    = Candidate


type CandidateGoal
    = CandidateGoal


type CandidateLogged
    = CandidateLogged


type Certification
    = Certification


type CertificationAuthority
    = CertificationAuthority


type CertificationPage
    = CertificationPage


type CertificationSummary
    = CertificationSummary


type ConventionCollective
    = ConventionCollective


type Degree
    = Degree


type Department
    = Department


type DepartmentWithOrganismMethods
    = DepartmentWithOrganismMethods


type Domaine
    = Domaine


type DropOutReason
    = DropOutReason


type ExamInfo
    = ExamInfo


type Experience
    = Experience


type Feasibility
    = Feasibility


type FeasibilityCountByCategory
    = FeasibilityCountByCategory


type FeasibilityPage
    = FeasibilityPage


type File
    = File


type FundingRequest
    = FundingRequest


type FundingRequestInformations
    = FundingRequestInformations


type FundingRequestUnifvae
    = FundingRequestUnifvae


type Goal
    = Goal


type Organism
    = Organism


type OrganismOnDepartment
    = OrganismOnDepartment


type PaginationInfo
    = PaginationInfo


type PaymentRequest
    = PaymentRequest


type Referential
    = Referential


type Region
    = Region


type ReorientationReason
    = ReorientationReason


type SubscriptionRequest
    = SubscriptionRequest


type SubscriptionRequestOnConventionCollective
    = SubscriptionRequestOnConventionCollective


type SubscriptionRequestOnDomaine
    = SubscriptionRequestOnDomaine


type SubscriptionRequestSummary
    = SubscriptionRequestSummary


type SubscriptionRequestsPaginated
    = SubscriptionRequestsPaginated


type Tokens
    = Tokens


type Training
    = Training


type TrainingForm
    = TrainingForm


type TypeDiplome
    = TypeDiplome


type VulnerabilityIndicator
    = VulnerabilityIndicator
