-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object exposing (..)


type Account
    = Account


type Admissibility
    = Admissibility


type BasicSkill
    = BasicSkill


type Candidacy
    = Candidacy


type CandidacyDropOut
    = CandidacyDropOut


type CandidacyStatus
    = CandidacyStatus


type CandidacySummary
    = CandidacySummary


type Candidate
    = Candidate


type CandidateGoal
    = CandidateGoal


type CandidateLogged
    = CandidateLogged


type Certification
    = Certification


type CertificationSummary
    = CertificationSummary


type Degree
    = Degree


type Department
    = Department


type DropOutReason
    = DropOutReason


type Experience
    = Experience


type FundingRequest
    = FundingRequest


type FundingRequestInformations
    = FundingRequestInformations


type Goal
    = Goal


type Organism
    = Organism


type Profession
    = Profession


type Referential
    = Referential


type Region
    = Region


type SearchCertificationsAndProfessionsResult
    = SearchCertificationsAndProfessionsResult


type Tokens
    = Tokens


type Training
    = Training


type TrainingForm
    = TrainingForm


type VulnerabilityIndicator
    = VulnerabilityIndicator
