-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Query exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias GetCandidacyRequiredArguments =
    { deviceId : Data.Scalar.Id }


getCandidacy :
    GetCandidacyRequiredArguments
    -> SelectionSet decodesTo Admin.Object.Candidacy
    -> SelectionSet (Maybe decodesTo) RootQuery
getCandidacy requiredArgs____ object____ =
    Object.selectionForCompositeField "getCandidacy" [ Argument.required "deviceId" requiredArgs____.deviceId (Data.Scalar.codecs |> Admin.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias GetCandidacyByIdRequiredArguments =
    { id : Data.Scalar.Id }


getCandidacyById :
    GetCandidacyByIdRequiredArguments
    -> SelectionSet decodesTo Admin.Object.Candidacy
    -> SelectionSet (Maybe decodesTo) RootQuery
getCandidacyById requiredArgs____ object____ =
    Object.selectionForCompositeField "getCandidacyById" [ Argument.required "id" requiredArgs____.id (Data.Scalar.codecs |> Admin.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


getCandidacies :
    SelectionSet decodesTo Admin.Object.CandidacySummary
    -> SelectionSet (List decodesTo) RootQuery
getCandidacies object____ =
    Object.selectionForCompositeField "getCandidacies" [] object____ (Basics.identity >> Decode.list)


getTrainings :
    SelectionSet decodesTo Admin.Object.Training
    -> SelectionSet (List decodesTo) RootQuery
getTrainings object____ =
    Object.selectionForCompositeField "getTrainings" [] object____ (Basics.identity >> Decode.list)


type alias GetOrganismsForCandidacyRequiredArguments =
    { candidacyId : Data.Scalar.Uuid }


getOrganismsForCandidacy :
    GetOrganismsForCandidacyRequiredArguments
    -> SelectionSet decodesTo Admin.Object.Organism
    -> SelectionSet (List decodesTo) RootQuery
getOrganismsForCandidacy requiredArgs____ object____ =
    Object.selectionForCompositeField "getOrganismsForCandidacy" [ Argument.required "candidacyId" requiredArgs____.candidacyId (Data.Scalar.codecs |> Admin.Scalar.unwrapEncoder .codecUuid) ] object____ (Basics.identity >> Decode.list)


getBasicSkills :
    SelectionSet decodesTo Admin.Object.BasicSkill
    -> SelectionSet (List decodesTo) RootQuery
getBasicSkills object____ =
    Object.selectionForCompositeField "getBasicSkills" [] object____ (Basics.identity >> Decode.list)


candidate_getCandidateWithCandidacy :
    SelectionSet decodesTo Admin.Object.Candidate
    -> SelectionSet decodesTo RootQuery
candidate_getCandidateWithCandidacy object____ =
    Object.selectionForCompositeField "candidate_getCandidateWithCandidacy" [] object____ Basics.identity


getReferential :
    SelectionSet decodesTo Admin.Object.Referential
    -> SelectionSet decodesTo RootQuery
getReferential object____ =
    Object.selectionForCompositeField "getReferential" [] object____ Basics.identity


type alias GetCertificationsRequiredArguments =
    { regionId : Data.Scalar.Uuid }


getCertifications :
    GetCertificationsRequiredArguments
    -> SelectionSet decodesTo Admin.Object.Certification
    -> SelectionSet (List decodesTo) RootQuery
getCertifications requiredArgs____ object____ =
    Object.selectionForCompositeField "getCertifications" [ Argument.required "regionId" requiredArgs____.regionId (Data.Scalar.codecs |> Admin.Scalar.unwrapEncoder .codecUuid) ] object____ (Basics.identity >> Decode.list)


getRegions :
    SelectionSet decodesTo Admin.Object.Region
    -> SelectionSet (List decodesTo) RootQuery
getRegions object____ =
    Object.selectionForCompositeField "getRegions" [] object____ (Basics.identity >> Decode.list)


getDegrees :
    SelectionSet decodesTo Admin.Object.Degree
    -> SelectionSet (List decodesTo) RootQuery
getDegrees object____ =
    Object.selectionForCompositeField "getDegrees" [] object____ (Basics.identity >> Decode.list)


getVulnerabilityIndicators :
    SelectionSet decodesTo Admin.Object.VulnerabilityIndicator
    -> SelectionSet (List decodesTo) RootQuery
getVulnerabilityIndicators object____ =
    Object.selectionForCompositeField "getVulnerabilityIndicators" [] object____ (Basics.identity >> Decode.list)


type alias SearchCertificationsAndProfessionsOptionalArguments =
    { query : OptionalArgument String }


searchCertificationsAndProfessions :
    (SearchCertificationsAndProfessionsOptionalArguments -> SearchCertificationsAndProfessionsOptionalArguments)
    -> SelectionSet decodesTo Admin.Object.SearchCertificationsAndProfessionsResult
    -> SelectionSet (Maybe decodesTo) RootQuery
searchCertificationsAndProfessions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { query = Absent }

        optionalArgs____ =
            [ Argument.optional "query" filledInOptionals____.query Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "searchCertificationsAndProfessions" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias GetCertificationRequiredArguments =
    { id : Data.Scalar.Id }


getCertification :
    GetCertificationRequiredArguments
    -> SelectionSet decodesTo Admin.Object.Certification
    -> SelectionSet (Maybe decodesTo) RootQuery
getCertification requiredArgs____ object____ =
    Object.selectionForCompositeField "getCertification" [ Argument.required "id" requiredArgs____.id (Data.Scalar.codecs |> Admin.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)
