-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.ScalarCodecs exposing (..)

import Admin.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Date =
    Admin.Scalar.Date


type alias Id =
    Admin.Scalar.Id


type alias Void =
    Admin.Scalar.Void


codecs : Admin.Scalar.Codecs Date Id Void
codecs =
    Admin.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecId = defaultCodecs.codecId
        , codecVoid = defaultCodecs.codecVoid
        }
