-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.ScalarCodecs exposing (..)

import Admin.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Admin.Scalar.Id


type alias Timestamp =
    Admin.Scalar.Timestamp


type alias Void =
    Admin.Scalar.Void


codecs : Admin.Scalar.Codecs Id Timestamp Void
codecs =
    Admin.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTimestamp = defaultCodecs.codecTimestamp
        , codecVoid = defaultCodecs.codecVoid
        }
