// Liste figée des comptes FranceConnect sandbox autorisés à être supprimés
// par la page de nettoyage. Toute modification de cette liste nécessite une
// revue produit: aucun autre compte ne peut être ciblé par ce module.
export const FRANCE_CONNECT_SANDBOX_EMAILS = [
  "wossewodda-3728@yopmail.com",
  "ymmyffarapp-1777@yopmail.com",
  "imyllommo-2736@yopmail.com",
  "cyxoxudaj-2393@yopmail.com",
  "test@yopmail.com",
  "lippizucis-4803@yopmail.com",
  "ecuhebup-9337@yopmail.com",
  "owallottim-1136@yopmail.com",
  "multiPrenom@france.fr",
  "effannopiq-4009@yopmail.com",
  "holisadduppe-5969@yopmail.com",
  "deseffesseupu-5120@yopmail.com",
  "tonegellaf-0100@yopmail.com",
  "minnannuxammi-4532@yopmail.com",
  "xagreureufadda-6730@yopmail.com",
  "yasser-martin@yopmail.com",
  "zalojummu-4690@yopmail.com",
  "nepocajapp-8174@yopmail.com",
  "etabage-0159@yopmail.com",
  "sans_tel@test.fr",
  "beitezeiteitou-9917@yopmail.com",
  "coimmettawawo-7344@yopmail.com",
  "mario.brosse@france.fr",
  "luigi.brosse@france.fr",
  "senossammab-2430@yopmail.com",
  "ammixaffa-0022@yopmail.com",
  "sanellaffilu-1962@yopmail.com",
  "cynnepovaz-0031@yopmail.com",
  "yttenneje-5416@yopmail.com",
  "inaqyzome-0621@yopmail.com",
  "nesspolynesie@yopmail.com",
  "ijujasa-5293@yopmail.com",
  "didejuttoja-8426@yopmail.com",
  "jean-fleuret@yopmail.com",
  "jean-targe@yopmail.com",
] as const;
