version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: reva
      POSTGRES_USER: reva
      POSTGRES_PASSWORD: password
    ports:
      - 5444:5432
