import { PrismaClient } from "@prisma/client";

const departments = [
  { label: "Ain", code: "01", codeRegion: "84" },
  { label: "Aisne", code: "02", codeRegion: "32" },
  { label: "Allier", code: "03", codeRegion: "84" },
  { label: "Alpes-de-Haute-Provence", code: "04", codeRegion: "93" },
  { label: "Hautes-Alpes", code: "05", codeRegion: "93" },
  { label: "Alpes-Maritimes", code: "06", codeRegion: "93" },
  { label: "Ardèche", code: "07", codeRegion: "84" },
  { label: "Ardennes", code: "08", codeRegion: "44" },
  { label: "Ariège", code: "09", codeRegion: "76" },
  { label: "Aube", code: "10", codeRegion: "44" },
  { label: "Aude", code: "11", codeRegion: "76" },
  { label: "Aveyron", code: "12", codeRegion: "76" },
  { label: "Bouches-du-Rhône", code: "13", codeRegion: "93" },
  { label: "Calvados", code: "14", codeRegion: "28" },
  { label: "Cantal", code: "15", codeRegion: "84" },
  { label: "Charente", code: "16", codeRegion: "75" },
  { label: "Charente-Maritime", code: "17", codeRegion: "75" },
  { label: "Cher", code: "18", codeRegion: "24" },
  { label: "Corrèze", code: "19", codeRegion: "75" },
  { label: "Côte-d'Or", code: "21", codeRegion: "27" },
  { label: "Côtes-d'Armor", code: "22", codeRegion: "53" },
  { label: "Creuse", code: "23", codeRegion: "75" },
  { label: "Dordogne", code: "24", codeRegion: "75" },
  { label: "Doubs", code: "25", codeRegion: "27" },
  { label: "Drôme", code: "26", codeRegion: "84" },
  { label: "Eure", code: "27", codeRegion: "28" },
  { label: "Eure-et-Loir", code: "28", codeRegion: "24" },
  { label: "Finistère", code: "29", codeRegion: "53" },
  { label: "Corse-du-Sud", code: "2A", codeRegion: "94" },
  { label: "Haute-Corse", code: "2B", codeRegion: "94" },
  { label: "Gard", code: "30", codeRegion: "76" },
  { label: "Haute-Garonne", code: "31", codeRegion: "76" },
  { label: "Gers", code: "32", codeRegion: "76" },
  { label: "Gironde", code: "33", codeRegion: "75" },
  { label: "Hérault", code: "34", codeRegion: "76" },
  { label: "Ille-et-Vilaine", code: "35", codeRegion: "53" },
  { label: "Indre", code: "36", codeRegion: "24" },
  { label: "Indre-et-Loire", code: "37", codeRegion: "24" },
  { label: "Isère", code: "38", codeRegion: "84" },
  { label: "Jura", code: "39", codeRegion: "27" },
  { label: "Landes", code: "40", codeRegion: "75" },
  { label: "Loir-et-Cher", code: "41", codeRegion: "24" },
  { label: "Loire", code: "42", codeRegion: "84" },
  { label: "Haute-Loire", code: "43", codeRegion: "84" },
  { label: "Loire-Atlantique", code: "44", codeRegion: "52" },
  { label: "Loiret", code: "45", codeRegion: "24" },
  { label: "Lot", code: "46", codeRegion: "76" },
  { label: "Lot-et-Garonne", code: "47", codeRegion: "75" },
  { label: "Lozère", code: "48", codeRegion: "76" },
  { label: "Maine-et-Loire", code: "49", codeRegion: "52" },
  { label: "Manche", code: "50", codeRegion: "28" },
  { label: "Marne", code: "51", codeRegion: "44" },
  { label: "Haute-Marne", code: "52", codeRegion: "44" },
  { label: "Mayenne", code: "53", codeRegion: "52" },
  { label: "Meurthe-et-Moselle", code: "54", codeRegion: "44" },
  { label: "Meuse", code: "55", codeRegion: "44" },
  { label: "Morbihan", code: "56", codeRegion: "53" },
  { label: "Moselle", code: "57", codeRegion: "44" },
  { label: "Nièvre", code: "58", codeRegion: "27" },
  { label: "Nord", code: "59", codeRegion: "32" },
  { label: "Oise", code: "60", codeRegion: "32" },
  { label: "Orne", code: "61", codeRegion: "28" },
  { label: "Pas-de-Calais", code: "62", codeRegion: "32" },
  { label: "Puy-de-Dôme", code: "63", codeRegion: "84" },
  { label: "Pyrénées-Atlantiques", code: "64", codeRegion: "75" },
  { label: "Hautes-Pyrénées", code: "65", codeRegion: "76" },
  { label: "Pyrénées-Orientales", code: "66", codeRegion: "76" },
  { label: "Bas-Rhin", code: "67", codeRegion: "44" },
  { label: "Haut-Rhin", code: "68", codeRegion: "44" },
  { label: "Rhône", code: "69", codeRegion: "84" },
  { label: "Haute-Saône", code: "70", codeRegion: "27" },
  { label: "Saône-et-Loire", code: "71", codeRegion: "27" },
  { label: "Sarthe", code: "72", codeRegion: "52" },
  { label: "Savoie", code: "73", codeRegion: "84" },
  { label: "Haute-Savoie", code: "74", codeRegion: "84" },
  { label: "Paris", code: "75", codeRegion: "11" },
  { label: "Seine-Maritime", code: "76", codeRegion: "28" },
  { label: "Seine-et-Marne", code: "77", codeRegion: "11" },
  { label: "Yvelines", code: "78", codeRegion: "11" },
  { label: "Deux-Sèvres", code: "79", codeRegion: "75" },
  { label: "Somme", code: "80", codeRegion: "32" },
  { label: "Tarn", code: "81", codeRegion: "76" },
  { label: "Tarn-et-Garonne", code: "82", codeRegion: "76" },
  { label: "Var", code: "83", codeRegion: "93" },
  { label: "Vaucluse", code: "84", codeRegion: "93" },
  { label: "Vendée", code: "85", codeRegion: "52" },
  { label: "Vienne", code: "86", codeRegion: "75" },
  { label: "Haute-Vienne", code: "87", codeRegion: "75" },
  { label: "Vosges", code: "88", codeRegion: "44" },
  { label: "Yonne", code: "89", codeRegion: "27" },
  { label: "Territoire de Belfort", code: "90", codeRegion: "27" },
  { label: "Essonne", code: "91", codeRegion: "11" },
  { label: "Hauts-de-Seine", code: "92", codeRegion: "11" },
  { label: "Seine-Saint-Denis", code: "93", codeRegion: "11" },
  { label: "Val-de-Marne", code: "94", codeRegion: "11" },
  { label: "Val-d'Oise", code: "95", codeRegion: "11" },
  { label: "Guadeloupe", code: "971", codeRegion: "01" },
  { label: "Martinique", code: "972", codeRegion: "02" },
  { label: "Guyane", code: "973", codeRegion: "03" },
  { label: "La Réunion", code: "974", codeRegion: "04" },
  { label: "Mayotte", code: "976", codeRegion: "06" },
];

export const insertDepartments = async (prisma: PrismaClient) => {
  const countDepartments = await prisma.department.count();

  if (countDepartments === 0) {
    for (const department of departments) {
      await prisma.department.create({
        data: {
          code: department.code,
          label: department.label,
          region: {
            connect: {
              code: department.codeRegion,
            },
          },
        },
      });
    }
  }
};
