-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Enum.CandidacyFeasibilityFormat exposing (..)

import Json.Decode as Decode exposing (Decoder)


type CandidacyFeasibilityFormat
    = UploadedPdf
    | Dematerialized


list : List CandidacyFeasibilityFormat
list =
    [ UploadedPdf, Dematerialized ]


decoder : Decoder CandidacyFeasibilityFormat
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "UPLOADED_PDF" ->
                        Decode.succeed UploadedPdf

                    "DEMATERIALIZED" ->
                        Decode.succeed Dematerialized

                    _ ->
                        Decode.fail ("Invalid CandidacyFeasibilityFormat type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : CandidacyFeasibilityFormat -> String
toString enum____ =
    case enum____ of
        UploadedPdf ->
            "UPLOADED_PDF"

        Dematerialized ->
            "DEMATERIALIZED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe CandidacyFeasibilityFormat
fromString enumString____ =
    case enumString____ of
        "UPLOADED_PDF" ->
            Just UploadedPdf

        "DEMATERIALIZED" ->
            Just Dematerialized

        _ ->
            Nothing
