-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Enum.CandidacyStatusFilter exposing (..)

import Json.Decode as Decode exposing (Decoder)


type CandidacyStatusFilter
    = ActiveHorsAbandon
    | Abandon
    | ReorienteeHorsAbandon
    | ArchiveHorsAbandonHorsReorientation
    | ParcoursConfirmeHorsAbandon
    | PriseEnChargeHorsAbandon
    | ParcoursEnvoyeHorsAbandon
    | DemandeFinancementEnvoyeHorsAbandon
    | DemandePaiementEnvoyeeHorsAbandon
    | ValidationHorsAbandon
    | ProjetHorsAbandon


list : List CandidacyStatusFilter
list =
    [ ActiveHorsAbandon, Abandon, ReorienteeHorsAbandon, ArchiveHorsAbandonHorsReorientation, ParcoursConfirmeHorsAbandon, PriseEnChargeHorsAbandon, ParcoursEnvoyeHorsAbandon, DemandeFinancementEnvoyeHorsAbandon, DemandePaiementEnvoyeeHorsAbandon, ValidationHorsAbandon, ProjetHorsAbandon ]


decoder : Decoder CandidacyStatusFilter
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ACTIVE_HORS_ABANDON" ->
                        Decode.succeed ActiveHorsAbandon

                    "ABANDON" ->
                        Decode.succeed Abandon

                    "REORIENTEE_HORS_ABANDON" ->
                        Decode.succeed ReorienteeHorsAbandon

                    "ARCHIVE_HORS_ABANDON_HORS_REORIENTATION" ->
                        Decode.succeed ArchiveHorsAbandonHorsReorientation

                    "PARCOURS_CONFIRME_HORS_ABANDON" ->
                        Decode.succeed ParcoursConfirmeHorsAbandon

                    "PRISE_EN_CHARGE_HORS_ABANDON" ->
                        Decode.succeed PriseEnChargeHorsAbandon

                    "PARCOURS_ENVOYE_HORS_ABANDON" ->
                        Decode.succeed ParcoursEnvoyeHorsAbandon

                    "DEMANDE_FINANCEMENT_ENVOYE_HORS_ABANDON" ->
                        Decode.succeed DemandeFinancementEnvoyeHorsAbandon

                    "DEMANDE_PAIEMENT_ENVOYEE_HORS_ABANDON" ->
                        Decode.succeed DemandePaiementEnvoyeeHorsAbandon

                    "VALIDATION_HORS_ABANDON" ->
                        Decode.succeed ValidationHorsAbandon

                    "PROJET_HORS_ABANDON" ->
                        Decode.succeed ProjetHorsAbandon

                    _ ->
                        Decode.fail ("Invalid CandidacyStatusFilter type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : CandidacyStatusFilter -> String
toString enum____ =
    case enum____ of
        ActiveHorsAbandon ->
            "ACTIVE_HORS_ABANDON"

        Abandon ->
            "ABANDON"

        ReorienteeHorsAbandon ->
            "REORIENTEE_HORS_ABANDON"

        ArchiveHorsAbandonHorsReorientation ->
            "ARCHIVE_HORS_ABANDON_HORS_REORIENTATION"

        ParcoursConfirmeHorsAbandon ->
            "PARCOURS_CONFIRME_HORS_ABANDON"

        PriseEnChargeHorsAbandon ->
            "PRISE_EN_CHARGE_HORS_ABANDON"

        ParcoursEnvoyeHorsAbandon ->
            "PARCOURS_ENVOYE_HORS_ABANDON"

        DemandeFinancementEnvoyeHorsAbandon ->
            "DEMANDE_FINANCEMENT_ENVOYE_HORS_ABANDON"

        DemandePaiementEnvoyeeHorsAbandon ->
            "DEMANDE_PAIEMENT_ENVOYEE_HORS_ABANDON"

        ValidationHorsAbandon ->
            "VALIDATION_HORS_ABANDON"

        ProjetHorsAbandon ->
            "PROJET_HORS_ABANDON"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe CandidacyStatusFilter
fromString enumString____ =
    case enumString____ of
        "ACTIVE_HORS_ABANDON" ->
            Just ActiveHorsAbandon

        "ABANDON" ->
            Just Abandon

        "REORIENTEE_HORS_ABANDON" ->
            Just ReorienteeHorsAbandon

        "ARCHIVE_HORS_ABANDON_HORS_REORIENTATION" ->
            Just ArchiveHorsAbandonHorsReorientation

        "PARCOURS_CONFIRME_HORS_ABANDON" ->
            Just ParcoursConfirmeHorsAbandon

        "PRISE_EN_CHARGE_HORS_ABANDON" ->
            Just PriseEnChargeHorsAbandon

        "PARCOURS_ENVOYE_HORS_ABANDON" ->
            Just ParcoursEnvoyeHorsAbandon

        "DEMANDE_FINANCEMENT_ENVOYE_HORS_ABANDON" ->
            Just DemandeFinancementEnvoyeHorsAbandon

        "DEMANDE_PAIEMENT_ENVOYEE_HORS_ABANDON" ->
            Just DemandePaiementEnvoyeeHorsAbandon

        "VALIDATION_HORS_ABANDON" ->
            Just ValidationHorsAbandon

        "PROJET_HORS_ABANDON" ->
            Just ProjetHorsAbandon

        _ ->
            Nothing
