-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Enum.CandidacyMenuEntryStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


type CandidacyMenuEntryStatus
    = Inactive
    | ActiveWithoutHint
    | ActiveWithEditHint


list : List CandidacyMenuEntryStatus
list =
    [ Inactive, ActiveWithoutHint, ActiveWithEditHint ]


decoder : Decoder CandidacyMenuEntryStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "INACTIVE" ->
                        Decode.succeed Inactive

                    "ACTIVE_WITHOUT_HINT" ->
                        Decode.succeed ActiveWithoutHint

                    "ACTIVE_WITH_EDIT_HINT" ->
                        Decode.succeed ActiveWithEditHint

                    _ ->
                        Decode.fail ("Invalid CandidacyMenuEntryStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : CandidacyMenuEntryStatus -> String
toString enum____ =
    case enum____ of
        Inactive ->
            "INACTIVE"

        ActiveWithoutHint ->
            "ACTIVE_WITHOUT_HINT"

        ActiveWithEditHint ->
            "ACTIVE_WITH_EDIT_HINT"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe CandidacyMenuEntryStatus
fromString enumString____ =
    case enumString____ of
        "INACTIVE" ->
            Just Inactive

        "ACTIVE_WITHOUT_HINT" ->
            Just ActiveWithoutHint

        "ACTIVE_WITH_EDIT_HINT" ->
            Just ActiveWithEditHint

        _ ->
            Nothing
