-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Enum.CertificationCompletion exposing (..)

import Json.Decode as Decode exposing (Decoder)


type CertificationCompletion
    = Complete
    | Partial


list : List CertificationCompletion
list =
    [ Complete, Partial ]


decoder : Decoder CertificationCompletion
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "COMPLETE" ->
                        Decode.succeed Complete

                    "PARTIAL" ->
                        Decode.succeed Partial

                    _ ->
                        Decode.fail ("Invalid CertificationCompletion type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : CertificationCompletion -> String
toString enum____ =
    case enum____ of
        Complete ->
            "COMPLETE"

        Partial ->
            "PARTIAL"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe CertificationCompletion
fromString enumString____ =
    case enumString____ of
        "COMPLETE" ->
            Just Complete

        "PARTIAL" ->
            Just Partial

        _ ->
            Nothing
