-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Enum.DFFileDecision exposing (..)

import Json.Decode as Decode exposing (Decoder)


type DFFileDecision
    = Accepted
    | Rejected


list : List DFFileDecision
list =
    [ Accepted, Rejected ]


decoder : Decoder DFFileDecision
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ACCEPTED" ->
                        Decode.succeed Accepted

                    "REJECTED" ->
                        Decode.succeed Rejected

                    _ ->
                        Decode.fail ("Invalid DFFileDecision type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : DFFileDecision -> String
toString enum____ =
    case enum____ of
        Accepted ->
            "ACCEPTED"

        Rejected ->
            "REJECTED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe DFFileDecision
fromString enumString____ =
    case enumString____ of
        "ACCEPTED" ->
            Just Accepted

        "REJECTED" ->
            Just Rejected

        _ ->
            Nothing
