-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Enum.SubscriptionOrganismTypology exposing (..)

import Json.Decode as Decode exposing (Decoder)


type SubscriptionOrganismTypology
    = Generaliste
    | ExpertFiliere
    | ExpertBranche


list : List SubscriptionOrganismTypology
list =
    [ Generaliste, ExpertFiliere, ExpertBranche ]


decoder : Decoder SubscriptionOrganismTypology
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "generaliste" ->
                        Decode.succeed Generaliste

                    "expertFiliere" ->
                        Decode.succeed ExpertFiliere

                    "expertBranche" ->
                        Decode.succeed ExpertBranche

                    _ ->
                        Decode.fail ("Invalid SubscriptionOrganismTypology type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SubscriptionOrganismTypology -> String
toString enum____ =
    case enum____ of
        Generaliste ->
            "generaliste"

        ExpertFiliere ->
            "expertFiliere"

        ExpertBranche ->
            "expertBranche"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SubscriptionOrganismTypology
fromString enumString____ =
    case enumString____ of
        "generaliste" ->
            Just Generaliste

        "expertFiliere" ->
            Just ExpertFiliere

        "expertBranche" ->
            Just ExpertBranche

        _ ->
            Nothing
