-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.Account exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

id : SelectionSet Data.Scalar.Uuid Admin.Object.Account
id =
      Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


keycloakId : SelectionSet String Admin.Object.Account
keycloakId =
      Object.selectionForField "String" "keycloakId" [] (Decode.string)


email : SelectionSet String Admin.Object.Account
email =
      Object.selectionForField "String" "email" [] (Decode.string)


firstname : SelectionSet (Maybe String) Admin.Object.Account
firstname =
      Object.selectionForField "(Maybe String)" "firstname" [] (Decode.string |> Decode.nullable)


lastname : SelectionSet (Maybe String) Admin.Object.Account
lastname =
      Object.selectionForField "(Maybe String)" "lastname" [] (Decode.string |> Decode.nullable)


organismId : SelectionSet (Maybe String) Admin.Object.Account
organismId =
      Object.selectionForField "(Maybe String)" "organismId" [] (Decode.string |> Decode.nullable)
