-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.Admissibility exposing (..)

import Admin.Enum.AdmissibilityStatus
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


isCandidateAlreadyAdmissible : SelectionSet Bool Admin.Object.Admissibility
isCandidateAlreadyAdmissible =
    Object.selectionForField "Bool" "isCandidateAlreadyAdmissible" [] Decode.bool


reportSentAt : SelectionSet (Maybe Data.Scalar.Timestamp) Admin.Object.Admissibility
reportSentAt =
    Object.selectionForField "(Maybe Data.Scalar.Timestamp)" "reportSentAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder |> Decode.nullable)


certifierRespondedAt : SelectionSet (Maybe Data.Scalar.Timestamp) Admin.Object.Admissibility
certifierRespondedAt =
    Object.selectionForField "(Maybe Data.Scalar.Timestamp)" "certifierRespondedAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder |> Decode.nullable)


responseAvailableToCandidateAt : SelectionSet (Maybe Data.Scalar.Timestamp) Admin.Object.Admissibility
responseAvailableToCandidateAt =
    Object.selectionForField "(Maybe Data.Scalar.Timestamp)" "responseAvailableToCandidateAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder |> Decode.nullable)


status : SelectionSet (Maybe Admin.Enum.AdmissibilityStatus.AdmissibilityStatus) Admin.Object.Admissibility
status =
    Object.selectionForField "(Maybe Enum.AdmissibilityStatus.AdmissibilityStatus)" "status" [] (Admin.Enum.AdmissibilityStatus.decoder |> Decode.nullable)
