-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.CandidateLogged exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


token : SelectionSet String Admin.Object.CandidateLogged
token =
    Object.selectionForField "String" "token" [] Decode.string


candidate :
    SelectionSet decodesTo Admin.Object.Candidate
    -> SelectionSet decodesTo Admin.Object.CandidateLogged
candidate object____ =
    Object.selectionForCompositeField "candidate" [] object____ Basics.identity
