-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.CandidacyMenu exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


menuHeader :
    SelectionSet decodesTo Admin.Object.CandidacyMenuEntry
    -> SelectionSet (List decodesTo) Admin.Object.CandidacyMenu
menuHeader object____ =
    Object.selectionForCompositeField "menuHeader" [] object____ (Basics.identity >> Decode.list)


mainMenu :
    SelectionSet decodesTo Admin.Object.CandidacyMenuEntry
    -> SelectionSet (List decodesTo) Admin.Object.CandidacyMenu
mainMenu object____ =
    Object.selectionForCompositeField "mainMenu" [] object____ (Basics.identity >> Decode.list)
