-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.Candidate exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet String Admin.Object.Candidate
id =
    Object.selectionForField "String" "id" [] Decode.string


firstname : SelectionSet String Admin.Object.Candidate
firstname =
    Object.selectionForField "String" "firstname" [] Decode.string


lastname : SelectionSet String Admin.Object.Candidate
lastname =
    Object.selectionForField "String" "lastname" [] Decode.string


email : SelectionSet String Admin.Object.Candidate
email =
    Object.selectionForField "String" "email" [] Decode.string


phone : SelectionSet String Admin.Object.Candidate
phone =
    Object.selectionForField "String" "phone" [] Decode.string


candidacy :
    SelectionSet decodesTo Admin.Object.Candidacy
    -> SelectionSet decodesTo Admin.Object.Candidate
candidacy object____ =
    Object.selectionForCompositeField "candidacy" [] object____ Basics.identity
