-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.CandidacyStatus exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.ScalarCodecs
import Admin.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Admin.ScalarCodecs.Id Admin.Object.CandidacyStatus
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Admin.ScalarCodecs.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


status : SelectionSet (Maybe String) Admin.Object.CandidacyStatus
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


createdAt : SelectionSet (Maybe Admin.ScalarCodecs.Date) Admin.Object.CandidacyStatus
createdAt =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "createdAt" [] (Admin.ScalarCodecs.codecs |> Admin.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)
