-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.CandidateGoal exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

goalId : SelectionSet Data.Scalar.Id Admin.Object.CandidateGoal
goalId =
      Object.selectionForField "Data.Scalar.Id" "goalId" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


additionalInformation : SelectionSet (Maybe String) Admin.Object.CandidateGoal
additionalInformation =
      Object.selectionForField "(Maybe String)" "additionalInformation" [] (Decode.string |> Decode.nullable)
