-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.CandidacyDropOut exposing (..)

import Admin.Enum.CandidacyStatusStep
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


dropOutReason :
    SelectionSet decodesTo Admin.Object.DropOutReason
    -> SelectionSet decodesTo Admin.Object.CandidacyDropOut
dropOutReason object____ =
    Object.selectionForCompositeField "dropOutReason" [] object____ Basics.identity


droppedOutAt : SelectionSet Data.Scalar.Timestamp Admin.Object.CandidacyDropOut
droppedOutAt =
    Object.selectionForField "Data.Scalar.Timestamp" "droppedOutAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


otherReasonContent : SelectionSet (Maybe String) Admin.Object.CandidacyDropOut
otherReasonContent =
    Object.selectionForField "(Maybe String)" "otherReasonContent" [] (Decode.string |> Decode.nullable)


status : SelectionSet Admin.Enum.CandidacyStatusStep.CandidacyStatusStep Admin.Object.CandidacyDropOut
status =
    Object.selectionForField "Enum.CandidacyStatusStep.CandidacyStatusStep" "status" [] Admin.Enum.CandidacyStatusStep.decoder
