-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.CandidateGoal exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


goalId : SelectionSet Data.Scalar.Id Admin.Object.CandidateGoal
goalId =
    Object.selectionForField "Data.Scalar.Id" "goalId" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


additionalInformation : SelectionSet (Maybe String) Admin.Object.CandidateGoal
additionalInformation =
    Object.selectionForField "(Maybe String)" "additionalInformation" [] (Decode.string |> Decode.nullable)
