-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.Candidate exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)
import Admin.Enum.Gender
id : SelectionSet Data.Scalar.Uuid Admin.Object.Candidate
id =
      Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


gender : SelectionSet (Maybe Admin.Enum.Gender.Gender) Admin.Object.Candidate
gender =
      Object.selectionForField "(Maybe Enum.Gender.Gender)" "gender" [] (Admin.Enum.Gender.decoder |> Decode.nullable)


firstname : SelectionSet String Admin.Object.Candidate
firstname =
      Object.selectionForField "String" "firstname" [] (Decode.string)


firstname2 : SelectionSet (Maybe String) Admin.Object.Candidate
firstname2 =
      Object.selectionForField "(Maybe String)" "firstname2" [] (Decode.string |> Decode.nullable)


firstname3 : SelectionSet (Maybe String) Admin.Object.Candidate
firstname3 =
      Object.selectionForField "(Maybe String)" "firstname3" [] (Decode.string |> Decode.nullable)


lastname : SelectionSet String Admin.Object.Candidate
lastname =
      Object.selectionForField "String" "lastname" [] (Decode.string)


email : SelectionSet String Admin.Object.Candidate
email =
      Object.selectionForField "String" "email" [] (Decode.string)


phone : SelectionSet String Admin.Object.Candidate
phone =
      Object.selectionForField "String" "phone" [] (Decode.string)


candidacy : SelectionSet decodesTo Admin.Object.Candidacy
 -> SelectionSet decodesTo Admin.Object.Candidate
candidacy object____ =
      Object.selectionForCompositeField "candidacy" [] (object____) (Basics.identity)


highestDegree : SelectionSet decodesTo Admin.Object.Degree
 -> SelectionSet (Maybe decodesTo) Admin.Object.Candidate
highestDegree object____ =
      Object.selectionForCompositeField "highestDegree" [] (object____) (Basics.identity >> Decode.nullable)


vulnerabilityIndicator : SelectionSet decodesTo Admin.Object.VulnerabilityIndicator
 -> SelectionSet (Maybe decodesTo) Admin.Object.Candidate
vulnerabilityIndicator object____ =
      Object.selectionForCompositeField "vulnerabilityIndicator" [] (object____) (Basics.identity >> Decode.nullable)
