-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.CandidateLogged exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

tokens : SelectionSet decodesTo Admin.Object.Tokens
 -> SelectionSet decodesTo Admin.Object.CandidateLogged
tokens object____ =
      Object.selectionForCompositeField "tokens" [] (object____) (Basics.identity)


candidate : SelectionSet decodesTo Admin.Object.Candidate
 -> SelectionSet decodesTo Admin.Object.CandidateLogged
candidate object____ =
      Object.selectionForCompositeField "candidate" [] (object____) (Basics.identity)
