-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.CandidacyStatus exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

id : SelectionSet Data.Scalar.Id Admin.Object.CandidacyStatus
id =
      Object.selectionForField "Data.Scalar.Id" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


status : SelectionSet String Admin.Object.CandidacyStatus
status =
      Object.selectionForField "String" "status" [] (Decode.string)


isActive : SelectionSet Bool Admin.Object.CandidacyStatus
isActive =
      Object.selectionForField "Bool" "isActive" [] (Decode.bool)


createdAt : SelectionSet Data.Scalar.Timestamp Admin.Object.CandidacyStatus
createdAt =
      Object.selectionForField "Data.Scalar.Timestamp" "createdAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)
