-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.CertificationAuthorityPaginated exposing (..)

import Admin.Object
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


rows :
    SelectionSet decodesTo Admin.Object.CertificationAuthority
    -> SelectionSet (List decodesTo) Admin.Object.CertificationAuthorityPaginated
rows object____ =
    Object.selectionForCompositeField "rows" [] object____ (Basics.identity >> Decode.list)


info :
    SelectionSet decodesTo Admin.Object.PaginationInfo
    -> SelectionSet decodesTo Admin.Object.CertificationAuthorityPaginated
info object____ =
    Object.selectionForCompositeField "info" [] object____ Basics.identity
