-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.Companion exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Id Admin.Object.Companion
id =
    Object.selectionForField "Data.Scalar.Id" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Admin.Object.Companion
name =
    Object.selectionForField "String" "name" [] Decode.string


street : SelectionSet String Admin.Object.Companion
street =
    Object.selectionForField "String" "street" [] Decode.string


city : SelectionSet String Admin.Object.Companion
city =
    Object.selectionForField "String" "city" [] Decode.string


zipCode : SelectionSet String Admin.Object.Companion
zipCode =
    Object.selectionForField "String" "zipCode" [] Decode.string
