-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.DFFCertificationCompetenceBloc exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


complete : SelectionSet Bool Admin.Object.DFFCertificationCompetenceBloc
complete =
    Object.selectionForField "Bool" "complete" [] Decode.bool


certificationCompetenceBloc :
    SelectionSet decodesTo Admin.Object.CertificationCompetenceBloc
    -> SelectionSet decodesTo Admin.Object.DFFCertificationCompetenceBloc
certificationCompetenceBloc object____ =
    Object.selectionForCompositeField "certificationCompetenceBloc" [] object____ Basics.identity
