-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.DossierDeValidationCountByCategory exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


all : SelectionSet Int Admin.Object.DossierDeValidationCountByCategory
all =
    Object.selectionForField "Int" "ALL" [] Decode.int


pending : SelectionSet Int Admin.Object.DossierDeValidationCountByCategory
pending =
    Object.selectionForField "Int" "PENDING" [] Decode.int


incomplete : SelectionSet Int Admin.Object.DossierDeValidationCountByCategory
incomplete =
    Object.selectionForField "Int" "INCOMPLETE" [] Decode.int
