-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.DropOutReasonOnCandidacy exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


dropOutReason :
    SelectionSet decodesTo Admin.Object.DropOutReason
    -> SelectionSet (Maybe decodesTo) Admin.Object.DropOutReasonOnCandidacy
dropOutReason object____ =
    Object.selectionForCompositeField "dropOutReason" [] object____ (Basics.identity >> Decode.nullable)


dropOutDate : SelectionSet (Maybe Data.Scalar.Timestamp) Admin.Object.DropOutReasonOnCandidacy
dropOutDate =
    Object.selectionForField "(Maybe Data.Scalar.Timestamp)" "dropOutDate" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder |> Decode.nullable)


otherReasonContent : SelectionSet (Maybe String) Admin.Object.DropOutReasonOnCandidacy
otherReasonContent =
    Object.selectionForField "(Maybe String)" "otherReasonContent" [] (Decode.string |> Decode.nullable)


status : SelectionSet (Maybe String) Admin.Object.DropOutReasonOnCandidacy
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)
