-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.FundingRequestInformations exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


training :
    SelectionSet decodesTo Admin.Object.TrainingForm
    -> SelectionSet decodesTo Admin.Object.FundingRequestInformations
training object____ =
    Object.selectionForCompositeField "training" [] object____ Basics.identity


fundingRequest :
    SelectionSet decodesTo Admin.Object.FundingRequest
    -> SelectionSet (Maybe decodesTo) Admin.Object.FundingRequestInformations
fundingRequest object____ =
    Object.selectionForCompositeField "fundingRequest" [] object____ (Basics.identity >> Decode.nullable)
