-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.FundingRequestInformations exposing (..)

import Admin.Object
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


training :
    SelectionSet decodesTo Admin.Object.TrainingForm
    -> SelectionSet decodesTo Admin.Object.FundingRequestInformations
training object____ =
    Object.selectionForCompositeField "training" [] object____ Basics.identity


fundingRequest :
    SelectionSet decodesTo Admin.Object.FundingRequest
    -> SelectionSet (Maybe decodesTo) Admin.Object.FundingRequestInformations
fundingRequest object____ =
    Object.selectionForCompositeField "fundingRequest" [] object____ (Basics.identity >> Decode.nullable)
