-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.FundingRequestUnifvae exposing (..)

import Admin.Enum.Gender
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.FundingRequestUnifvae
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


candidateFirstname : SelectionSet String Admin.Object.FundingRequestUnifvae
candidateFirstname =
    Object.selectionForField "String" "candidateFirstname" [] Decode.string


candidateSecondname : SelectionSet (Maybe String) Admin.Object.FundingRequestUnifvae
candidateSecondname =
    Object.selectionForField "(Maybe String)" "candidateSecondname" [] (Decode.string |> Decode.nullable)


candidateThirdname : SelectionSet (Maybe String) Admin.Object.FundingRequestUnifvae
candidateThirdname =
    Object.selectionForField "(Maybe String)" "candidateThirdname" [] (Decode.string |> Decode.nullable)


candidateLastname : SelectionSet String Admin.Object.FundingRequestUnifvae
candidateLastname =
    Object.selectionForField "String" "candidateLastname" [] Decode.string


candidateGender : SelectionSet Admin.Enum.Gender.Gender Admin.Object.FundingRequestUnifvae
candidateGender =
    Object.selectionForField "Enum.Gender.Gender" "candidateGender" [] Admin.Enum.Gender.decoder


companion :
    SelectionSet decodesTo Admin.Object.Organism
    -> SelectionSet (Maybe decodesTo) Admin.Object.FundingRequestUnifvae
companion object____ =
    Object.selectionForCompositeField "companion" [] object____ (Basics.identity >> Decode.nullable)


individualHourCount : SelectionSet Int Admin.Object.FundingRequestUnifvae
individualHourCount =
    Object.selectionForField "Int" "individualHourCount" [] Decode.int


individualCost : SelectionSet Data.Scalar.Decimal Admin.Object.FundingRequestUnifvae
individualCost =
    Object.selectionForField "Data.Scalar.Decimal" "individualCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


collectiveHourCount : SelectionSet Int Admin.Object.FundingRequestUnifvae
collectiveHourCount =
    Object.selectionForField "Int" "collectiveHourCount" [] Decode.int


collectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.FundingRequestUnifvae
collectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "collectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


basicSkills :
    SelectionSet decodesTo Admin.Object.BasicSkill
    -> SelectionSet (List decodesTo) Admin.Object.FundingRequestUnifvae
basicSkills object____ =
    Object.selectionForCompositeField "basicSkills" [] object____ (Basics.identity >> Decode.list)


basicSkillsHourCount : SelectionSet Int Admin.Object.FundingRequestUnifvae
basicSkillsHourCount =
    Object.selectionForField "Int" "basicSkillsHourCount" [] Decode.int


basicSkillsCost : SelectionSet Data.Scalar.Decimal Admin.Object.FundingRequestUnifvae
basicSkillsCost =
    Object.selectionForField "Data.Scalar.Decimal" "basicSkillsCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


mandatoryTrainings :
    SelectionSet decodesTo Admin.Object.Training
    -> SelectionSet (List decodesTo) Admin.Object.FundingRequestUnifvae
mandatoryTrainings object____ =
    Object.selectionForCompositeField "mandatoryTrainings" [] object____ (Basics.identity >> Decode.list)


mandatoryTrainingsHourCount : SelectionSet Int Admin.Object.FundingRequestUnifvae
mandatoryTrainingsHourCount =
    Object.selectionForField "Int" "mandatoryTrainingsHourCount" [] Decode.int


mandatoryTrainingsCost : SelectionSet Data.Scalar.Decimal Admin.Object.FundingRequestUnifvae
mandatoryTrainingsCost =
    Object.selectionForField "Data.Scalar.Decimal" "mandatoryTrainingsCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


certificateSkills : SelectionSet String Admin.Object.FundingRequestUnifvae
certificateSkills =
    Object.selectionForField "String" "certificateSkills" [] Decode.string


certificateSkillsHourCount : SelectionSet Int Admin.Object.FundingRequestUnifvae
certificateSkillsHourCount =
    Object.selectionForField "Int" "certificateSkillsHourCount" [] Decode.int


certificateSkillsCost : SelectionSet Data.Scalar.Decimal Admin.Object.FundingRequestUnifvae
certificateSkillsCost =
    Object.selectionForField "Data.Scalar.Decimal" "certificateSkillsCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


otherTraining : SelectionSet String Admin.Object.FundingRequestUnifvae
otherTraining =
    Object.selectionForField "String" "otherTraining" [] Decode.string


otherTrainingHourCount : SelectionSet Int Admin.Object.FundingRequestUnifvae
otherTrainingHourCount =
    Object.selectionForField "Int" "otherTrainingHourCount" [] Decode.int


otherTrainingCost : SelectionSet Data.Scalar.Decimal Admin.Object.FundingRequestUnifvae
otherTrainingCost =
    Object.selectionForField "Data.Scalar.Decimal" "otherTrainingCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)
