-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.FundingRequestUnifvae exposing (..)

import Admin.Enum.Gender
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.FundingRequestUnifvae
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


candidateFirstname : SelectionSet String Admin.Object.FundingRequestUnifvae
candidateFirstname =
    Object.selectionForField "String" "candidateFirstname" [] Decode.string


candidateSecondname : SelectionSet (Maybe String) Admin.Object.FundingRequestUnifvae
candidateSecondname =
    Object.selectionForField "(Maybe String)" "candidateSecondname" [] (Decode.string |> Decode.nullable)


candidateThirdname : SelectionSet (Maybe String) Admin.Object.FundingRequestUnifvae
candidateThirdname =
    Object.selectionForField "(Maybe String)" "candidateThirdname" [] (Decode.string |> Decode.nullable)


candidateLastname : SelectionSet String Admin.Object.FundingRequestUnifvae
candidateLastname =
    Object.selectionForField "String" "candidateLastname" [] Decode.string


candidateGender : SelectionSet Admin.Enum.Gender.Gender Admin.Object.FundingRequestUnifvae
candidateGender =
    Object.selectionForField "Enum.Gender.Gender" "candidateGender" [] Admin.Enum.Gender.decoder


isPartialCertification : SelectionSet Bool Admin.Object.FundingRequestUnifvae
isPartialCertification =
    Object.selectionForField "Bool" "isPartialCertification" [] Decode.bool


companion :
    SelectionSet decodesTo Admin.Object.Organism
    -> SelectionSet (Maybe decodesTo) Admin.Object.FundingRequestUnifvae
companion object____ =
    Object.selectionForCompositeField "companion" [] object____ (Basics.identity >> Decode.nullable)


individualHourCount : SelectionSet Float Admin.Object.FundingRequestUnifvae
individualHourCount =
    Object.selectionForField "Float" "individualHourCount" [] Decode.float


individualCost : SelectionSet Float Admin.Object.FundingRequestUnifvae
individualCost =
    Object.selectionForField "Float" "individualCost" [] Decode.float


collectiveHourCount : SelectionSet Float Admin.Object.FundingRequestUnifvae
collectiveHourCount =
    Object.selectionForField "Float" "collectiveHourCount" [] Decode.float


collectiveCost : SelectionSet Float Admin.Object.FundingRequestUnifvae
collectiveCost =
    Object.selectionForField "Float" "collectiveCost" [] Decode.float


basicSkills :
    SelectionSet decodesTo Admin.Object.BasicSkill
    -> SelectionSet (List decodesTo) Admin.Object.FundingRequestUnifvae
basicSkills object____ =
    Object.selectionForCompositeField "basicSkills" [] object____ (Basics.identity >> Decode.list)


basicSkillsHourCount : SelectionSet Float Admin.Object.FundingRequestUnifvae
basicSkillsHourCount =
    Object.selectionForField "Float" "basicSkillsHourCount" [] Decode.float


basicSkillsCost : SelectionSet Float Admin.Object.FundingRequestUnifvae
basicSkillsCost =
    Object.selectionForField "Float" "basicSkillsCost" [] Decode.float


mandatoryTrainings :
    SelectionSet decodesTo Admin.Object.Training
    -> SelectionSet (List decodesTo) Admin.Object.FundingRequestUnifvae
mandatoryTrainings object____ =
    Object.selectionForCompositeField "mandatoryTrainings" [] object____ (Basics.identity >> Decode.list)


mandatoryTrainingsHourCount : SelectionSet Float Admin.Object.FundingRequestUnifvae
mandatoryTrainingsHourCount =
    Object.selectionForField "Float" "mandatoryTrainingsHourCount" [] Decode.float


mandatoryTrainingsCost : SelectionSet Float Admin.Object.FundingRequestUnifvae
mandatoryTrainingsCost =
    Object.selectionForField "Float" "mandatoryTrainingsCost" [] Decode.float


certificateSkills : SelectionSet String Admin.Object.FundingRequestUnifvae
certificateSkills =
    Object.selectionForField "String" "certificateSkills" [] Decode.string


certificateSkillsHourCount : SelectionSet Float Admin.Object.FundingRequestUnifvae
certificateSkillsHourCount =
    Object.selectionForField "Float" "certificateSkillsHourCount" [] Decode.float


certificateSkillsCost : SelectionSet Float Admin.Object.FundingRequestUnifvae
certificateSkillsCost =
    Object.selectionForField "Float" "certificateSkillsCost" [] Decode.float


otherTraining : SelectionSet String Admin.Object.FundingRequestUnifvae
otherTraining =
    Object.selectionForField "String" "otherTraining" [] Decode.string


otherTrainingHourCount : SelectionSet Float Admin.Object.FundingRequestUnifvae
otherTrainingHourCount =
    Object.selectionForField "Float" "otherTrainingHourCount" [] Decode.float


otherTrainingCost : SelectionSet Float Admin.Object.FundingRequestUnifvae
otherTrainingCost =
    Object.selectionForField "Float" "otherTrainingCost" [] Decode.float
