-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.FundingRequest exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.FundingRequest
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


companionId : SelectionSet Data.Scalar.Uuid Admin.Object.FundingRequest
companionId =
    Object.selectionForField "Data.Scalar.Uuid" "companionId" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


diagnosisHourCount : SelectionSet Int Admin.Object.FundingRequest
diagnosisHourCount =
    Object.selectionForField "Int" "diagnosisHourCount" [] Decode.int


diagnosisCost : SelectionSet Int Admin.Object.FundingRequest
diagnosisCost =
    Object.selectionForField "Int" "diagnosisCost" [] Decode.int


postExamHourCount : SelectionSet Int Admin.Object.FundingRequest
postExamHourCount =
    Object.selectionForField "Int" "postExamHourCount" [] Decode.int


postExamCost : SelectionSet Int Admin.Object.FundingRequest
postExamCost =
    Object.selectionForField "Int" "postExamCost" [] Decode.int


individualHourCount : SelectionSet Int Admin.Object.FundingRequest
individualHourCount =
    Object.selectionForField "Int" "individualHourCount" [] Decode.int


individualCost : SelectionSet Int Admin.Object.FundingRequest
individualCost =
    Object.selectionForField "Int" "individualCost" [] Decode.int


collectiveHourCount : SelectionSet Int Admin.Object.FundingRequest
collectiveHourCount =
    Object.selectionForField "Int" "collectiveHourCount" [] Decode.int


collectiveCost : SelectionSet Int Admin.Object.FundingRequest
collectiveCost =
    Object.selectionForField "Int" "collectiveCost" [] Decode.int


basicSkills :
    SelectionSet decodesTo Admin.Object.BasicSkill
    -> SelectionSet (List decodesTo) Admin.Object.FundingRequest
basicSkills object____ =
    Object.selectionForCompositeField "basicSkills" [] object____ (Basics.identity >> Decode.list)


basicSkillsHourCount : SelectionSet Int Admin.Object.FundingRequest
basicSkillsHourCount =
    Object.selectionForField "Int" "basicSkillsHourCount" [] Decode.int


basicSkillsCost : SelectionSet Int Admin.Object.FundingRequest
basicSkillsCost =
    Object.selectionForField "Int" "basicSkillsCost" [] Decode.int


mandatoryTrainings :
    SelectionSet decodesTo Admin.Object.Training
    -> SelectionSet (List decodesTo) Admin.Object.FundingRequest
mandatoryTrainings object____ =
    Object.selectionForCompositeField "mandatoryTrainings" [] object____ (Basics.identity >> Decode.list)


mandatoryTrainingsHourCount : SelectionSet Int Admin.Object.FundingRequest
mandatoryTrainingsHourCount =
    Object.selectionForField "Int" "mandatoryTrainingsHourCount" [] Decode.int


mandatoryTrainingsCost : SelectionSet Int Admin.Object.FundingRequest
mandatoryTrainingsCost =
    Object.selectionForField "Int" "mandatoryTrainingsCost" [] Decode.int


certificateSkills : SelectionSet String Admin.Object.FundingRequest
certificateSkills =
    Object.selectionForField "String" "certificateSkills" [] Decode.string


certificateSkillsHourCount : SelectionSet Int Admin.Object.FundingRequest
certificateSkillsHourCount =
    Object.selectionForField "Int" "certificateSkillsHourCount" [] Decode.int


certificateSkillsCost : SelectionSet Int Admin.Object.FundingRequest
certificateSkillsCost =
    Object.selectionForField "Int" "certificateSkillsCost" [] Decode.int


otherTraining : SelectionSet String Admin.Object.FundingRequest
otherTraining =
    Object.selectionForField "String" "otherTraining" [] Decode.string


otherTrainingHourCount : SelectionSet Int Admin.Object.FundingRequest
otherTrainingHourCount =
    Object.selectionForField "Int" "otherTrainingHourCount" [] Decode.int


otherTrainingCost : SelectionSet Int Admin.Object.FundingRequest
otherTrainingCost =
    Object.selectionForField "Int" "otherTrainingCost" [] Decode.int


examHourCount : SelectionSet Int Admin.Object.FundingRequest
examHourCount =
    Object.selectionForField "Int" "examHourCount" [] Decode.int


examCost : SelectionSet Int Admin.Object.FundingRequest
examCost =
    Object.selectionForField "Int" "examCost" [] Decode.int
