-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.Goal exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

id : SelectionSet Data.Scalar.Id Admin.Object.Goal
id =
      Object.selectionForField "Data.Scalar.Id" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


label : SelectionSet String Admin.Object.Goal
label =
      Object.selectionForField "String" "label" [] (Decode.string)


order : SelectionSet Int Admin.Object.Goal
order =
      Object.selectionForField "Int" "order" [] (Decode.int)


needsAdditionalInformation : SelectionSet Bool Admin.Object.Goal
needsAdditionalInformation =
      Object.selectionForField "Bool" "needsAdditionalInformation" [] (Decode.bool)


isActive : SelectionSet Bool Admin.Object.Goal
isActive =
      Object.selectionForField "Bool" "isActive" [] (Decode.bool)
