-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.MaisonMereAAP exposing (..)

import Admin.Enum.LegalStatus
import Admin.Enum.OrganismTypology
import Admin.Enum.StatutValidationInformationsJuridiquesMaisonMereAAP
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.MaisonMereAAP
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


raisonSociale : SelectionSet String Admin.Object.MaisonMereAAP
raisonSociale =
    Object.selectionForField "String" "raisonSociale" [] Decode.string


statutJuridique : SelectionSet Admin.Enum.LegalStatus.LegalStatus Admin.Object.MaisonMereAAP
statutJuridique =
    Object.selectionForField "Enum.LegalStatus.LegalStatus" "statutJuridique" [] Admin.Enum.LegalStatus.decoder


siret : SelectionSet String Admin.Object.MaisonMereAAP
siret =
    Object.selectionForField "String" "siret" [] Decode.string


phone : SelectionSet (Maybe String) Admin.Object.MaisonMereAAP
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


typologie : SelectionSet Admin.Enum.OrganismTypology.OrganismTypology Admin.Object.MaisonMereAAP
typologie =
    Object.selectionForField "Enum.OrganismTypology.OrganismTypology" "typologie" [] Admin.Enum.OrganismTypology.decoder


siteWeb : SelectionSet (Maybe String) Admin.Object.MaisonMereAAP
siteWeb =
    Object.selectionForField "(Maybe String)" "siteWeb" [] (Decode.string |> Decode.nullable)


dateExpirationCertificationQualiopi : SelectionSet (Maybe Data.Scalar.Timestamp) Admin.Object.MaisonMereAAP
dateExpirationCertificationQualiopi =
    Object.selectionForField "(Maybe Data.Scalar.Timestamp)" "dateExpirationCertificationQualiopi" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder |> Decode.nullable)


gestionnaire :
    SelectionSet decodesTo Admin.Object.Account
    -> SelectionSet decodesTo Admin.Object.MaisonMereAAP
gestionnaire object____ =
    Object.selectionForCompositeField "gestionnaire" [] object____ Basics.identity


organisms :
    SelectionSet decodesTo Admin.Object.Organism
    -> SelectionSet (List decodesTo) Admin.Object.MaisonMereAAP
organisms object____ =
    Object.selectionForCompositeField "organisms" [] object____ (Basics.identity >> Decode.list)


statutValidationInformationsJuridiquesMaisonMereAAP : SelectionSet Admin.Enum.StatutValidationInformationsJuridiquesMaisonMereAAP.StatutValidationInformationsJuridiquesMaisonMereAAP Admin.Object.MaisonMereAAP
statutValidationInformationsJuridiquesMaisonMereAAP =
    Object.selectionForField "Enum.StatutValidationInformationsJuridiquesMaisonMereAAP.StatutValidationInformationsJuridiquesMaisonMereAAP" "statutValidationInformationsJuridiquesMaisonMereAAP" [] Admin.Enum.StatutValidationInformationsJuridiquesMaisonMereAAP.decoder


maisonMereAAPOnDepartements :
    SelectionSet decodesTo Admin.Object.MaisonMereAAPOnDepartment
    -> SelectionSet (List decodesTo) Admin.Object.MaisonMereAAP
maisonMereAAPOnDepartements object____ =
    Object.selectionForCompositeField "maisonMereAAPOnDepartements" [] object____ (Basics.identity >> Decode.list)


maisonMereAAPOnConventionCollectives :
    SelectionSet decodesTo Admin.Object.MaisonMereAAPOnConventionCollective
    -> SelectionSet (List decodesTo) Admin.Object.MaisonMereAAP
maisonMereAAPOnConventionCollectives object____ =
    Object.selectionForCompositeField "maisonMereAAPOnConventionCollectives" [] object____ (Basics.identity >> Decode.list)


type alias LegalInformationDocumentsDecisionsOptionalArguments =
    { input : OptionalArgument Admin.InputObject.MaisonMereAAPLegalInformationDocumentsDecisionsInput }


legalInformationDocumentsDecisions :
    (LegalInformationDocumentsDecisionsOptionalArguments -> LegalInformationDocumentsDecisionsOptionalArguments)
    -> SelectionSet decodesTo Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
    -> SelectionSet (List decodesTo) Admin.Object.MaisonMereAAP
legalInformationDocumentsDecisions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { input = Absent }

        optionalArgs____ =
            [ Argument.optional "input" filledInOptionals____.input Admin.InputObject.encodeMaisonMereAAPLegalInformationDocumentsDecisionsInput ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "legalInformationDocumentsDecisions" optionalArgs____ object____ (Basics.identity >> Decode.list)


createdAt : SelectionSet Data.Scalar.Timestamp Admin.Object.MaisonMereAAP
createdAt =
    Object.selectionForField "Data.Scalar.Timestamp" "createdAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


legalInformationDocuments :
    SelectionSet decodesTo Admin.Object.MaisonMereAAPLegalInformationDocuments
    -> SelectionSet (Maybe decodesTo) Admin.Object.MaisonMereAAP
legalInformationDocuments object____ =
    Object.selectionForCompositeField "legalInformationDocuments" [] object____ (Basics.identity >> Decode.nullable)
