-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.MaisonMereAAPCGU exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


version : SelectionSet (Maybe Int) Admin.Object.MaisonMereAAPCGU
version =
    Object.selectionForField "(Maybe Int)" "version" [] (Decode.int |> Decode.nullable)


acceptedAt : SelectionSet (Maybe Data.Scalar.Timestamp) Admin.Object.MaisonMereAAPCGU
acceptedAt =
    Object.selectionForField "(Maybe Data.Scalar.Timestamp)" "acceptedAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder |> Decode.nullable)


isLatestVersion : SelectionSet Bool Admin.Object.MaisonMereAAPCGU
isLatestVersion =
    Object.selectionForField "Bool" "isLatestVersion" [] Decode.bool
