-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.MaisonMereAAP exposing (..)

import Admin.Enum.OrganismTypology
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.MaisonMereAAP
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


label : SelectionSet String Admin.Object.MaisonMereAAP
label =
    Object.selectionForField "String" "label" [] Decode.string


address : SelectionSet String Admin.Object.MaisonMereAAP
address =
    Object.selectionForField "String" "address" [] Decode.string


zip : SelectionSet String Admin.Object.MaisonMereAAP
zip =
    Object.selectionForField "String" "zip" [] Decode.string


city : SelectionSet String Admin.Object.MaisonMereAAP
city =
    Object.selectionForField "String" "city" [] Decode.string


contactAdministrativeEmail : SelectionSet String Admin.Object.MaisonMereAAP
contactAdministrativeEmail =
    Object.selectionForField "String" "contactAdministrativeEmail" [] Decode.string


contactAdministrativePhone : SelectionSet (Maybe String) Admin.Object.MaisonMereAAP
contactAdministrativePhone =
    Object.selectionForField "(Maybe String)" "contactAdministrativePhone" [] (Decode.string |> Decode.nullable)


website : SelectionSet (Maybe String) Admin.Object.MaisonMereAAP
website =
    Object.selectionForField "(Maybe String)" "website" [] (Decode.string |> Decode.nullable)


typology : SelectionSet Admin.Enum.OrganismTypology.OrganismTypology Admin.Object.MaisonMereAAP
typology =
    Object.selectionForField "Enum.OrganismTypology.OrganismTypology" "typology" [] Admin.Enum.OrganismTypology.decoder


isActive : SelectionSet Bool Admin.Object.MaisonMereAAP
isActive =
    Object.selectionForField "Bool" "isActive" [] Decode.bool


agences :
    SelectionSet decodesTo Admin.Object.Organism
    -> SelectionSet (List decodesTo) Admin.Object.MaisonMereAAP
agences object____ =
    Object.selectionForCompositeField "agences" [] object____ (Basics.identity >> Decode.list)


maisonMereAAPOnDepartements :
    SelectionSet decodesTo Admin.Object.MaisonMereAAPOnDepartment
    -> SelectionSet (List decodesTo) Admin.Object.MaisonMereAAP
maisonMereAAPOnDepartements object____ =
    Object.selectionForCompositeField "maisonMereAAPOnDepartements" [] object____ (Basics.identity >> Decode.list)
