-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision exposing (..)

import Admin.Enum.MaisonMereAAPLegalInformationDocumentsDecisionEnum
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


decision : SelectionSet Admin.Enum.MaisonMereAAPLegalInformationDocumentsDecisionEnum.MaisonMereAAPLegalInformationDocumentsDecisionEnum Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
decision =
    Object.selectionForField "Enum.MaisonMereAAPLegalInformationDocumentsDecisionEnum.MaisonMereAAPLegalInformationDocumentsDecisionEnum" "decision" [] Admin.Enum.MaisonMereAAPLegalInformationDocumentsDecisionEnum.decoder


internalComment : SelectionSet String Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
internalComment =
    Object.selectionForField "String" "internalComment" [] Decode.string


aapComment : SelectionSet String Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
aapComment =
    Object.selectionForField "String" "aapComment" [] Decode.string


aapUpdatedDocumentsAt : SelectionSet Data.Scalar.Timestamp Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
aapUpdatedDocumentsAt =
    Object.selectionForField "Data.Scalar.Timestamp" "aapUpdatedDocumentsAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


decisionTakenAt : SelectionSet Data.Scalar.Timestamp Admin.Object.MaisonMereAAPLegalInformationDocumentsDecision
decisionTakenAt =
    Object.selectionForField "Data.Scalar.Timestamp" "decisionTakenAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)
