-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.MandataireSocial exposing (..)

import Admin.Enum.PersonneType
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type_ : SelectionSet Admin.Enum.PersonneType.PersonneType Admin.Object.MandataireSocial
type_ =
    Object.selectionForField "Enum.PersonneType.PersonneType" "type" [] Admin.Enum.PersonneType.decoder


nom : SelectionSet String Admin.Object.MandataireSocial
nom =
    Object.selectionForField "String" "nom" [] Decode.string


fonction : SelectionSet (Maybe String) Admin.Object.MandataireSocial
fonction =
    Object.selectionForField "(Maybe String)" "fonction" [] (Decode.string |> Decode.nullable)
