-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.OrganismOnDegree exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Uuid Admin.Object.OrganismOnDegree
id =
    Object.selectionForField "Data.Scalar.Uuid" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


organism :
    SelectionSet decodesTo Admin.Object.Organism
    -> SelectionSet decodesTo Admin.Object.OrganismOnDegree
organism object____ =
    Object.selectionForCompositeField "organism" [] object____ Basics.identity


degree :
    SelectionSet decodesTo Admin.Object.Degree
    -> SelectionSet decodesTo Admin.Object.OrganismOnDegree
degree object____ =
    Object.selectionForCompositeField "degree" [] object____ Basics.identity
