-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.PaymentRequest exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Id Admin.Object.PaymentRequest
id =
    Object.selectionForField "Data.Scalar.Id" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


diagnosisEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
diagnosisEffectiveHourCount =
    Object.selectionForField "Int" "diagnosisEffectiveHourCount" [] Decode.int


postExamEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
postExamEffectiveHourCount =
    Object.selectionForField "Int" "postExamEffectiveHourCount" [] Decode.int


individualEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
individualEffectiveHourCount =
    Object.selectionForField "Int" "individualEffectiveHourCount" [] Decode.int


collectiveEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
collectiveEffectiveHourCount =
    Object.selectionForField "Int" "collectiveEffectiveHourCount" [] Decode.int


mandatoryTrainingsEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
mandatoryTrainingsEffectiveHourCount =
    Object.selectionForField "Int" "mandatoryTrainingsEffectiveHourCount" [] Decode.int


basicSkillsEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
basicSkillsEffectiveHourCount =
    Object.selectionForField "Int" "basicSkillsEffectiveHourCount" [] Decode.int


certificateSkillsEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
certificateSkillsEffectiveHourCount =
    Object.selectionForField "Int" "certificateSkillsEffectiveHourCount" [] Decode.int


examEffectiveHourCount : SelectionSet Int Admin.Object.PaymentRequest
examEffectiveHourCount =
    Object.selectionForField "Int" "examEffectiveHourCount" [] Decode.int


invoiceNumber : SelectionSet String Admin.Object.PaymentRequest
invoiceNumber =
    Object.selectionForField "String" "invoiceNumber" [] Decode.string
