-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.PaymentRequestUnifvae exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Id Admin.Object.PaymentRequestUnifvae
id =
    Object.selectionForField "Data.Scalar.Id" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


individualEffectiveHourCount : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
individualEffectiveHourCount =
    Object.selectionForField "Data.Scalar.Decimal" "individualEffectiveHourCount" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


individualEffectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
individualEffectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "individualEffectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


collectiveEffectiveHourCount : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
collectiveEffectiveHourCount =
    Object.selectionForField "Data.Scalar.Decimal" "collectiveEffectiveHourCount" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


collectiveEffectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
collectiveEffectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "collectiveEffectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


mandatoryTrainingsEffectiveHourCount : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
mandatoryTrainingsEffectiveHourCount =
    Object.selectionForField "Data.Scalar.Decimal" "mandatoryTrainingsEffectiveHourCount" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


mandatoryTrainingsEffectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
mandatoryTrainingsEffectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "mandatoryTrainingsEffectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


basicSkillsEffectiveHourCount : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
basicSkillsEffectiveHourCount =
    Object.selectionForField "Data.Scalar.Decimal" "basicSkillsEffectiveHourCount" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


basicSkillsEffectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
basicSkillsEffectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "basicSkillsEffectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


certificateSkillsEffectiveHourCount : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
certificateSkillsEffectiveHourCount =
    Object.selectionForField "Data.Scalar.Decimal" "certificateSkillsEffectiveHourCount" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


certificateSkillsEffectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
certificateSkillsEffectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "certificateSkillsEffectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


otherTrainingEffectiveHourCount : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
otherTrainingEffectiveHourCount =
    Object.selectionForField "Data.Scalar.Decimal" "otherTrainingEffectiveHourCount" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


otherTrainingEffectiveCost : SelectionSet Data.Scalar.Decimal Admin.Object.PaymentRequestUnifvae
otherTrainingEffectiveCost =
    Object.selectionForField "Data.Scalar.Decimal" "otherTrainingEffectiveCost" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


invoiceNumber : SelectionSet String Admin.Object.PaymentRequestUnifvae
invoiceNumber =
    Object.selectionForField "String" "invoiceNumber" [] Decode.string
