-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.SearchCertificationsAndProfessionsResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

certifications : SelectionSet decodesTo Admin.Object.Certification
 -> SelectionSet (List decodesTo) Admin.Object.SearchCertificationsAndProfessionsResult
certifications object____ =
      Object.selectionForCompositeField "certifications" [] (object____) (Basics.identity >> Decode.list)


professions : SelectionSet decodesTo Admin.Object.Profession
 -> SelectionSet (List decodesTo) Admin.Object.SearchCertificationsAndProfessionsResult
professions object____ =
      Object.selectionForCompositeField "professions" [] (object____) (Basics.identity >> Decode.list)
