-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.SubscriptionRequest exposing (..)

import Admin.Enum.LegalStatus
import Admin.Enum.SubscriptionRequestStatus
import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Data.Scalar.Id Admin.Object.SubscriptionRequest
id =
    Object.selectionForField "Data.Scalar.Id" "id" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecId |> .decoder)


companySiret : SelectionSet String Admin.Object.SubscriptionRequest
companySiret =
    Object.selectionForField "String" "companySiret" [] Decode.string


companyLegalStatus : SelectionSet Admin.Enum.LegalStatus.LegalStatus Admin.Object.SubscriptionRequest
companyLegalStatus =
    Object.selectionForField "Enum.LegalStatus.LegalStatus" "companyLegalStatus" [] Admin.Enum.LegalStatus.decoder


companyName : SelectionSet String Admin.Object.SubscriptionRequest
companyName =
    Object.selectionForField "String" "companyName" [] Decode.string


managerFirstname : SelectionSet String Admin.Object.SubscriptionRequest
managerFirstname =
    Object.selectionForField "String" "managerFirstname" [] Decode.string


managerLastname : SelectionSet String Admin.Object.SubscriptionRequest
managerLastname =
    Object.selectionForField "String" "managerLastname" [] Decode.string


accountFirstname : SelectionSet String Admin.Object.SubscriptionRequest
accountFirstname =
    Object.selectionForField "String" "accountFirstname" [] Decode.string


accountLastname : SelectionSet String Admin.Object.SubscriptionRequest
accountLastname =
    Object.selectionForField "String" "accountLastname" [] Decode.string


accountEmail : SelectionSet String Admin.Object.SubscriptionRequest
accountEmail =
    Object.selectionForField "String" "accountEmail" [] Decode.string


accountPhoneNumber : SelectionSet String Admin.Object.SubscriptionRequest
accountPhoneNumber =
    Object.selectionForField "String" "accountPhoneNumber" [] Decode.string


companyWebsite : SelectionSet String Admin.Object.SubscriptionRequest
companyWebsite =
    Object.selectionForField "String" "companyWebsite" [] Decode.string


delegataire : SelectionSet Bool Admin.Object.SubscriptionRequest
delegataire =
    Object.selectionForField "Bool" "delegataire" [] Decode.bool


status : SelectionSet Admin.Enum.SubscriptionRequestStatus.SubscriptionRequestStatus Admin.Object.SubscriptionRequest
status =
    Object.selectionForField "Enum.SubscriptionRequestStatus.SubscriptionRequestStatus" "status" [] Admin.Enum.SubscriptionRequestStatus.decoder


rejectionReason : SelectionSet (Maybe String) Admin.Object.SubscriptionRequest
rejectionReason =
    Object.selectionForField "(Maybe String)" "rejectionReason" [] (Decode.string |> Decode.nullable)


internalComment : SelectionSet (Maybe String) Admin.Object.SubscriptionRequest
internalComment =
    Object.selectionForField "(Maybe String)" "internalComment" [] (Decode.string |> Decode.nullable)


attestationURSSAFFile :
    SelectionSet decodesTo Admin.Object.File
    -> SelectionSet decodesTo Admin.Object.SubscriptionRequest
attestationURSSAFFile object____ =
    Object.selectionForCompositeField "attestationURSSAFFile" [] object____ Basics.identity


justificatifIdentiteDirigeantFile :
    SelectionSet decodesTo Admin.Object.File
    -> SelectionSet decodesTo Admin.Object.SubscriptionRequest
justificatifIdentiteDirigeantFile object____ =
    Object.selectionForCompositeField "justificatifIdentiteDirigeantFile" [] object____ Basics.identity


lettreDeDelegationFile :
    SelectionSet decodesTo Admin.Object.File
    -> SelectionSet (Maybe decodesTo) Admin.Object.SubscriptionRequest
lettreDeDelegationFile object____ =
    Object.selectionForCompositeField "lettreDeDelegationFile" [] object____ (Basics.identity >> Decode.nullable)


justificatifIdentiteDelegataireFile :
    SelectionSet decodesTo Admin.Object.File
    -> SelectionSet (Maybe decodesTo) Admin.Object.SubscriptionRequest
justificatifIdentiteDelegataireFile object____ =
    Object.selectionForCompositeField "justificatifIdentiteDelegataireFile" [] object____ (Basics.identity >> Decode.nullable)


createdAt : SelectionSet Data.Scalar.Timestamp Admin.Object.SubscriptionRequest
createdAt =
    Object.selectionForField "Data.Scalar.Timestamp" "createdAt" [] (Data.Scalar.codecs |> Admin.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


etablissement :
    SelectionSet decodesTo Admin.Object.Etablissement
    -> SelectionSet (Maybe decodesTo) Admin.Object.SubscriptionRequest
etablissement object____ =
    Object.selectionForCompositeField "etablissement" [] object____ (Basics.identity >> Decode.nullable)
