-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Admin.Object.Tokens exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Admin.Object
import Admin.Interface
import Admin.Union
import Admin.Scalar
import Admin.InputObject
import Data.Scalar
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

accessToken : SelectionSet String Admin.Object.Tokens
accessToken =
      Object.selectionForField "String" "accessToken" [] (Decode.string)


refreshToken : SelectionSet String Admin.Object.Tokens
refreshToken =
      Object.selectionForField "String" "refreshToken" [] (Decode.string)


idToken : SelectionSet String Admin.Object.Tokens
idToken =
      Object.selectionForField "String" "idToken" [] (Decode.string)
