-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Admin.Object.TrainingForm exposing (..)

import Admin.InputObject
import Admin.Interface
import Admin.Object
import Admin.Scalar
import Admin.Union
import Data.Scalar
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


individualHourCount : SelectionSet Int Admin.Object.TrainingForm
individualHourCount =
    Object.selectionForField "Int" "individualHourCount" [] Decode.int


collectiveHourCount : SelectionSet Int Admin.Object.TrainingForm
collectiveHourCount =
    Object.selectionForField "Int" "collectiveHourCount" [] Decode.int


basicSkills :
    SelectionSet decodesTo Admin.Object.BasicSkill
    -> SelectionSet (List decodesTo) Admin.Object.TrainingForm
basicSkills object____ =
    Object.selectionForCompositeField "basicSkills" [] object____ (Basics.identity >> Decode.list)


mandatoryTrainings :
    SelectionSet decodesTo Admin.Object.Training
    -> SelectionSet (List decodesTo) Admin.Object.TrainingForm
mandatoryTrainings object____ =
    Object.selectionForCompositeField "mandatoryTrainings" [] object____ (Basics.identity >> Decode.list)


certificateSkills : SelectionSet String Admin.Object.TrainingForm
certificateSkills =
    Object.selectionForField "String" "certificateSkills" [] Decode.string


otherTraining : SelectionSet String Admin.Object.TrainingForm
otherTraining =
    Object.selectionForField "String" "otherTraining" [] Decode.string
