insert into
    role_permission_vae_collective (role, permission)
values
    ('ADMINISTRATEUR_PORTEUR_DE_PROJET', 'MODIFIER_COHORTE'),
    ('ADMINISTRATEUR_PORTEUR_DE_PROJET', 'SUPPRIMER_COHORTE'),
    ('ADMINISTRATEUR_PORTEUR_DE_PROJET', 'VOIR_LISTE_COHORTES'),
    ('ADMINISTRATEUR_PORTEUR_DE_PROJET', 'VOIR_COHORTE'),
    ('ADMINISTRATEUR_PORTEUR_DE_PROJET', 'VOIR_STATISTIQUES');
