-- AlterTable
ALTER TABLE "candidate" ADD COLUMN     "birth_city" VARCHAR(255),
ADD COLUMN     "birth_department_id" UUID,
ADD COLUMN     "birthdate" TIMESTAMPTZ(6),
ADD COLUMN     "country_id" UUID,
ADD COLUMN     "nationality" VARCHAR(255),
ADD COLUMN     "securite_sociale_number" VARCHAR(255),
ADD COLUMN     "usename" VARCHAR(255);

-- CreateTable
CREATE TABLE "country" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "label" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6),

    CONSTRAINT "country_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "country_label_key" ON "country"("label");

-- AddForeignKey
ALTER TABLE "candidate" ADD CONSTRAINT "candidate_birth_department_id_fkey" FOREIGN KEY ("birth_department_id") REFERENCES "department"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "candidate" ADD CONSTRAINT "candidate_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "country" (label) VALUES
('Afghanistan'),
('Albanie'),
('Algérie'),
('Andorre'),
('Angola'),
('Antigua-et-Barbuda'),
('Argentine'),
('Arménie'),
('Australie'),
('Autriche'),
('Azerbaïdjan'),
('Bahamas'),
('Bahreïn'),
('Bangladesh'),
('Barbade'),
('Biélorussie'),
('Belgique'),
('Belize'),
('Bénin'),
('Bhoutan'),
('Bolivie'),
('Bosnie-Herzégovine'),
('Botswana'),
('Brésil'),
('Brunei'),
('Bulgarie'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodge'),
('Cameroun'),
('Canada'),
('République centrafricaine'),
('Tchad'),
('Chili'),
('Chine'),
('Colombie'),
('Comores'),
('Congo (Congo-Brazzaville)'),
('Costa Rica'),
('Croatie'),
('Cuba'),
('Chypre'),
('République tchèque (Tchéquie)'),
('Danemark'),
('Djibouti'),
('Dominique'),
('République dominicaine'),
('Équateur'),
('Égypte'),
('Salvador'),
('Guinée équatoriale'),
('Érythrée'),
('Estonie'),
('Éthiopie'),
('Fidji'),
('Finlande'),
('France'),
('Gabon'),
('Gambie'),
('Géorgie'),
('Allemagne'),
('Ghana'),
('Grèce'),
('Grenade'),
('Guatemala'),
('Guinée'),
('Guinée-Bissau'),
('Guyane'),
('Haïti'),
('Honduras'),
('Hongrie'),
('Islande'),
('Inde'),
('Indonésie'),
('Iran'),
('Irak'),
('Irlande'),
('Israël'),
('Italie'),
('Jamaïque'),
('Japon'),
('Jordanie'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Koweït'),
('Kirghizistan'),
('Laos'),
('Lettonie'),
('Liban'),
('Lesotho'),
('Liberia'),
('Libye'),
('Liechtenstein'),
('Lituanie'),
('Luxembourg'),
('Macédoine du Nord'),
('Madagascar'),
('Malawi'),
('Malaisie'),
('Maldives'),
('Mali'),
('Malte'),
('Îles Marshall'),
('Mauritanie'),
('Maurice'),
('Mexique'),
('Micronésie'),
('Moldavie'),
('Monaco'),
('Mongolie'),
('Monténégro'),
('Maroc'),
('Mozambique'),
('Myanmar (Birmanie)'),
('Namibie'),
('Nauru'),
('Népal'),
('Pays-Bas'),
('Nouvelle-Zélande'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Corée du Nord'),
('Norvège'),
('Oman'),
('Pakistan'),
('Palaos'),
('Palestine'),
('Panama'),
('Papouasie-Nouvelle-Guinée'),
('Paraguay'),
('Pérou'),
('Philippines'),
('Pologne'),
('Portugal'),
('Qatar'),
('Roumanie'),
('Russie'),
('Rwanda'),
('Saint-Kitts-et-Nevis'),
('Sainte-Lucie'),
('Saint-Vincent-et-les Grenadines'),
('Samoa'),
('Saint-Marin'),
('Sao Tomé-et-Principe'),
('Arabie Saoudite'),
('Sénégal'),
('Serbie'),
('Seychelles'),
('Sierra Leone'),
('Singapour'),
('Slovaquie'),
('Slovénie'),
('Îles Salomon'),
('Somalie'),
('Afrique du Sud'),
('Corée du Sud'),
('Sud-Soudan'),
('Espagne'),
('Sri Lanka'),
('Soudan'),
('Suriname'),
('Suède'),
('Suisse'),
('Syrie'),
('Tajikistan'),
('Tanzanie'),
('Thaïlande'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinité-et-Tobago'),
('Tunisie'),
('Turquie'),
('Turkménistan'),
('Tuvalu'),
('Ouganda'),
('Ukraine'),
('Émirats arabes unis'),
('Royaume-Uni'),
('États-Unis'),
('Uruguay'),
('Ouzbékistan'),
('Vanuatu'),
('Cité du Vatican'),
('Venezuela'),
('Vietnam'),
('Yémen'),
('Zambie'),
('Zimbabwe');
