/*
  Warnings:

  - A unique constraint covering the columns `[insee_code]` on the table `country` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `insee_code` to the `country` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable: add column as nullable so existing rows can be updated
ALTER TABLE "country" ADD COLUMN "insee_code" VARCHAR(5);

-- Populate insee_code with COG (Code Officiel Géographique) for each country
UPDATE "country" SET "insee_code" = '99236' WHERE "label" = 'Taïwan';
UPDATE "country" SET "insee_code" = '99212' WHERE "label" = 'Afghanistan';
UPDATE "country" SET "insee_code" = '99303' WHERE "label" = 'Afrique du Sud';
UPDATE "country" SET "insee_code" = '99125' WHERE "label" = 'Albanie';
UPDATE "country" SET "insee_code" = '99352' WHERE "label" = 'Algérie';
UPDATE "country" SET "insee_code" = '99109' WHERE "label" = 'Allemagne';
UPDATE "country" SET "insee_code" = '99130' WHERE "label" = 'Andorre';
UPDATE "country" SET "insee_code" = '99395' WHERE "label" = 'Angola';
UPDATE "country" SET "insee_code" = '99441' WHERE "label" = 'Antigua-et-Barbuda';
UPDATE "country" SET "insee_code" = '99201' WHERE "label" = 'Arabie Saoudite';
UPDATE "country" SET "insee_code" = '99415' WHERE "label" = 'Argentine';
UPDATE "country" SET "insee_code" = '99252' WHERE "label" = 'Arménie';
UPDATE "country" SET "insee_code" = '99501' WHERE "label" = 'Australie';
UPDATE "country" SET "insee_code" = '99110' WHERE "label" = 'Autriche';
UPDATE "country" SET "insee_code" = '99253' WHERE "label" = 'Azerbaïdjan';
UPDATE "country" SET "insee_code" = '99436' WHERE "label" = 'Bahamas';
UPDATE "country" SET "insee_code" = '99249' WHERE "label" = 'Bahreïn';
UPDATE "country" SET "insee_code" = '99246' WHERE "label" = 'Bangladesh';
UPDATE "country" SET "insee_code" = '99434' WHERE "label" = 'Barbade';
UPDATE "country" SET "insee_code" = '99131' WHERE "label" = 'Belgique';
UPDATE "country" SET "insee_code" = '99429' WHERE "label" = 'Belize';
UPDATE "country" SET "insee_code" = '99327' WHERE "label" = 'Bénin';
UPDATE "country" SET "insee_code" = '99214' WHERE "label" = 'Bhoutan';
UPDATE "country" SET "insee_code" = '99148' WHERE "label" = 'Biélorussie';
UPDATE "country" SET "insee_code" = '99418' WHERE "label" = 'Bolivie';
UPDATE "country" SET "insee_code" = '99118' WHERE "label" = 'Bosnie-Herzégovine';
UPDATE "country" SET "insee_code" = '99347' WHERE "label" = 'Botswana';
UPDATE "country" SET "insee_code" = '99416' WHERE "label" = 'Brésil';
UPDATE "country" SET "insee_code" = '99225' WHERE "label" = 'Brunei';
UPDATE "country" SET "insee_code" = '99111' WHERE "label" = 'Bulgarie';
UPDATE "country" SET "insee_code" = '99331' WHERE "label" = 'Burkina Faso';
UPDATE "country" SET "insee_code" = '99321' WHERE "label" = 'Burundi';
UPDATE "country" SET "insee_code" = '99396' WHERE "label" = 'Cabo Verde';
UPDATE "country" SET "insee_code" = '99234' WHERE "label" = 'Cambodge';
UPDATE "country" SET "insee_code" = '99322' WHERE "label" = 'Cameroun';
UPDATE "country" SET "insee_code" = '99401' WHERE "label" = 'Canada';
UPDATE "country" SET "insee_code" = '99417' WHERE "label" = 'Chili';
UPDATE "country" SET "insee_code" = '99216' WHERE "label" = 'Chine';
UPDATE "country" SET "insee_code" = '99254' WHERE "label" = 'Chypre';
UPDATE "country" SET "insee_code" = '99129' WHERE "label" = 'Cité du Vatican';
UPDATE "country" SET "insee_code" = '99419' WHERE "label" = 'Colombie';
UPDATE "country" SET "insee_code" = '99397' WHERE "label" = 'Comores';
UPDATE "country" SET "insee_code" = '99324' WHERE "label" = 'Congo (Congo-Brazzaville)';
UPDATE "country" SET "insee_code" = '99238' WHERE "label" = 'Corée du Nord';
UPDATE "country" SET "insee_code" = '99239' WHERE "label" = 'Corée du Sud';
UPDATE "country" SET "insee_code" = '99406' WHERE "label" = 'Costa Rica';
UPDATE "country" SET "insee_code" = '99326' WHERE "label" = 'Côte d''Ivoire';
UPDATE "country" SET "insee_code" = '99119' WHERE "label" = 'Croatie';
UPDATE "country" SET "insee_code" = '99407' WHERE "label" = 'Cuba';
UPDATE "country" SET "insee_code" = '99101' WHERE "label" = 'Danemark';
UPDATE "country" SET "insee_code" = '99399' WHERE "label" = 'Djibouti';
UPDATE "country" SET "insee_code" = '99438' WHERE "label" = 'Dominique';
UPDATE "country" SET "insee_code" = '99301' WHERE "label" = 'Égypte';
UPDATE "country" SET "insee_code" = '99247' WHERE "label" = 'Émirats arabes unis';
UPDATE "country" SET "insee_code" = '99420' WHERE "label" = 'Équateur';
UPDATE "country" SET "insee_code" = '99317' WHERE "label" = 'Érythrée';
UPDATE "country" SET "insee_code" = '99134' WHERE "label" = 'Espagne';
UPDATE "country" SET "insee_code" = '99106' WHERE "label" = 'Estonie';
UPDATE "country" SET "insee_code" = '99404' WHERE "label" = 'États-Unis';
UPDATE "country" SET "insee_code" = '99315' WHERE "label" = 'Éthiopie';
UPDATE "country" SET "insee_code" = '99508' WHERE "label" = 'Fidji';
UPDATE "country" SET "insee_code" = '99105' WHERE "label" = 'Finlande';
UPDATE "country" SET "insee_code" = '99100' WHERE "label" = 'France';
UPDATE "country" SET "insee_code" = '99328' WHERE "label" = 'Gabon';
UPDATE "country" SET "insee_code" = '99304' WHERE "label" = 'Gambie';
UPDATE "country" SET "insee_code" = '99255' WHERE "label" = 'Géorgie';
UPDATE "country" SET "insee_code" = '99329' WHERE "label" = 'Ghana';
UPDATE "country" SET "insee_code" = '99126' WHERE "label" = 'Grèce';
UPDATE "country" SET "insee_code" = '99435' WHERE "label" = 'Grenade';
UPDATE "country" SET "insee_code" = '99409' WHERE "label" = 'Guatemala';
UPDATE "country" SET "insee_code" = '99330' WHERE "label" = 'Guinée';
UPDATE "country" SET "insee_code" = '99392' WHERE "label" = 'Guinée-Bissau';
UPDATE "country" SET "insee_code" = '99314' WHERE "label" = 'Guinée équatoriale';
UPDATE "country" SET "insee_code" = '99428' WHERE "label" = 'Guyane';
UPDATE "country" SET "insee_code" = '99410' WHERE "label" = 'Haïti';
UPDATE "country" SET "insee_code" = '99411' WHERE "label" = 'Honduras';
UPDATE "country" SET "insee_code" = '99112' WHERE "label" = 'Hongrie';
UPDATE "country" SET "insee_code" = '99515' WHERE "label" = 'Îles Marshall';
UPDATE "country" SET "insee_code" = '99512' WHERE "label" = 'Îles Salomon';
UPDATE "country" SET "insee_code" = '99223' WHERE "label" = 'Inde';
UPDATE "country" SET "insee_code" = '99231' WHERE "label" = 'Indonésie';
UPDATE "country" SET "insee_code" = '99203' WHERE "label" = 'Irak';
UPDATE "country" SET "insee_code" = '99204' WHERE "label" = 'Iran';
UPDATE "country" SET "insee_code" = '99136' WHERE "label" = 'Irlande';
UPDATE "country" SET "insee_code" = '99102' WHERE "label" = 'Islande';
UPDATE "country" SET "insee_code" = '99207' WHERE "label" = 'Israël';
UPDATE "country" SET "insee_code" = '99127' WHERE "label" = 'Italie';
UPDATE "country" SET "insee_code" = '99426' WHERE "label" = 'Jamaïque';
UPDATE "country" SET "insee_code" = '99217' WHERE "label" = 'Japon';
UPDATE "country" SET "insee_code" = '99222' WHERE "label" = 'Jordanie';
UPDATE "country" SET "insee_code" = '99256' WHERE "label" = 'Kazakhstan';
UPDATE "country" SET "insee_code" = '99332' WHERE "label" = 'Kenya';
UPDATE "country" SET "insee_code" = '99257' WHERE "label" = 'Kirghizistan';
UPDATE "country" SET "insee_code" = '99513' WHERE "label" = 'Kiribati';
UPDATE "country" SET "insee_code" = '99157' WHERE "label" = 'Kosovo';
UPDATE "country" SET "insee_code" = '99240' WHERE "label" = 'Koweït';
UPDATE "country" SET "insee_code" = '99241' WHERE "label" = 'Laos';
UPDATE "country" SET "insee_code" = '99348' WHERE "label" = 'Lesotho';
UPDATE "country" SET "insee_code" = '99107' WHERE "label" = 'Lettonie';
UPDATE "country" SET "insee_code" = '99205' WHERE "label" = 'Liban';
UPDATE "country" SET "insee_code" = '99302' WHERE "label" = 'Liberia';
UPDATE "country" SET "insee_code" = '99316' WHERE "label" = 'Libye';
UPDATE "country" SET "insee_code" = '99113' WHERE "label" = 'Liechtenstein';
UPDATE "country" SET "insee_code" = '99108' WHERE "label" = 'Lituanie';
UPDATE "country" SET "insee_code" = '99137' WHERE "label" = 'Luxembourg';
UPDATE "country" SET "insee_code" = '99156' WHERE "label" = 'Macédoine du Nord';
UPDATE "country" SET "insee_code" = '99333' WHERE "label" = 'Madagascar';
UPDATE "country" SET "insee_code" = '99227' WHERE "label" = 'Malaisie';
UPDATE "country" SET "insee_code" = '99334' WHERE "label" = 'Malawi';
UPDATE "country" SET "insee_code" = '99229' WHERE "label" = 'Maldives';
UPDATE "country" SET "insee_code" = '99335' WHERE "label" = 'Mali';
UPDATE "country" SET "insee_code" = '99144' WHERE "label" = 'Malte';
UPDATE "country" SET "insee_code" = '99350' WHERE "label" = 'Maroc';
UPDATE "country" SET "insee_code" = '99390' WHERE "label" = 'Maurice';
UPDATE "country" SET "insee_code" = '99336' WHERE "label" = 'Mauritanie';
UPDATE "country" SET "insee_code" = '99405' WHERE "label" = 'Mexique';
UPDATE "country" SET "insee_code" = '99516' WHERE "label" = 'Micronésie';
UPDATE "country" SET "insee_code" = '99151' WHERE "label" = 'Moldavie';
UPDATE "country" SET "insee_code" = '99138' WHERE "label" = 'Monaco';
UPDATE "country" SET "insee_code" = '99242' WHERE "label" = 'Mongolie';
UPDATE "country" SET "insee_code" = '99120' WHERE "label" = 'Monténégro';
UPDATE "country" SET "insee_code" = '99393' WHERE "label" = 'Mozambique';
UPDATE "country" SET "insee_code" = '99224' WHERE "label" = 'Myanmar (Birmanie)';
UPDATE "country" SET "insee_code" = '99311' WHERE "label" = 'Namibie';
UPDATE "country" SET "insee_code" = '99507' WHERE "label" = 'Nauru';
UPDATE "country" SET "insee_code" = '99215' WHERE "label" = 'Népal';
UPDATE "country" SET "insee_code" = '99412' WHERE "label" = 'Nicaragua';
UPDATE "country" SET "insee_code" = '99337' WHERE "label" = 'Niger';
UPDATE "country" SET "insee_code" = '99338' WHERE "label" = 'Nigeria';
UPDATE "country" SET "insee_code" = '99103' WHERE "label" = 'Norvège';
UPDATE "country" SET "insee_code" = '99502' WHERE "label" = 'Nouvelle-Zélande';
UPDATE "country" SET "insee_code" = '99250' WHERE "label" = 'Oman';
UPDATE "country" SET "insee_code" = '99339' WHERE "label" = 'Ouganda';
UPDATE "country" SET "insee_code" = '99258' WHERE "label" = 'Ouzbékistan';
UPDATE "country" SET "insee_code" = '99213' WHERE "label" = 'Pakistan';
UPDATE "country" SET "insee_code" = '99517' WHERE "label" = 'Palaos';
UPDATE "country" SET "insee_code" = '99261' WHERE "label" = 'Palestine';
UPDATE "country" SET "insee_code" = '99413' WHERE "label" = 'Panama';
UPDATE "country" SET "insee_code" = '99510' WHERE "label" = 'Papouasie-Nouvelle-Guinée';
UPDATE "country" SET "insee_code" = '99421' WHERE "label" = 'Paraguay';
UPDATE "country" SET "insee_code" = '99135' WHERE "label" = 'Pays-Bas';
UPDATE "country" SET "insee_code" = '99422' WHERE "label" = 'Pérou';
UPDATE "country" SET "insee_code" = '99220' WHERE "label" = 'Philippines';
UPDATE "country" SET "insee_code" = '99122' WHERE "label" = 'Pologne';
UPDATE "country" SET "insee_code" = '99139' WHERE "label" = 'Portugal';
UPDATE "country" SET "insee_code" = '99248' WHERE "label" = 'Qatar';
UPDATE "country" SET "insee_code" = '99323' WHERE "label" = 'République centrafricaine';
UPDATE "country" SET "insee_code" = '99312' WHERE "label" = 'République démocratique du Congo';
UPDATE "country" SET "insee_code" = '99408' WHERE "label" = 'République dominicaine';
UPDATE "country" SET "insee_code" = '99116' WHERE "label" = 'République tchèque (Tchéquie)';
UPDATE "country" SET "insee_code" = '99114' WHERE "label" = 'Roumanie';
UPDATE "country" SET "insee_code" = '99132' WHERE "label" = 'Royaume-Uni';
UPDATE "country" SET "insee_code" = '99123' WHERE "label" = 'Russie';
UPDATE "country" SET "insee_code" = '99340' WHERE "label" = 'Rwanda';
UPDATE "country" SET "insee_code" = '99439' WHERE "label" = 'Sainte-Lucie';
UPDATE "country" SET "insee_code" = '99442' WHERE "label" = 'Saint-Kitts-et-Nevis';
UPDATE "country" SET "insee_code" = '99128' WHERE "label" = 'Saint-Marin';
UPDATE "country" SET "insee_code" = '99440' WHERE "label" = 'Saint-Vincent-et-les Grenadines';
UPDATE "country" SET "insee_code" = '99414' WHERE "label" = 'Salvador';
UPDATE "country" SET "insee_code" = '99506' WHERE "label" = 'Samoa';
UPDATE "country" SET "insee_code" = '99394' WHERE "label" = 'Sao Tomé-et-Principe';
UPDATE "country" SET "insee_code" = '99341' WHERE "label" = 'Sénégal';
UPDATE "country" SET "insee_code" = '99121' WHERE "label" = 'Serbie';
UPDATE "country" SET "insee_code" = '99398' WHERE "label" = 'Seychelles';
UPDATE "country" SET "insee_code" = '99342' WHERE "label" = 'Sierra Leone';
UPDATE "country" SET "insee_code" = '99226' WHERE "label" = 'Singapour';
UPDATE "country" SET "insee_code" = '99117' WHERE "label" = 'Slovaquie';
UPDATE "country" SET "insee_code" = '99145' WHERE "label" = 'Slovénie';
UPDATE "country" SET "insee_code" = '99318' WHERE "label" = 'Somalie';
UPDATE "country" SET "insee_code" = '99343' WHERE "label" = 'Soudan';
UPDATE "country" SET "insee_code" = '99235' WHERE "label" = 'Sri Lanka';
UPDATE "country" SET "insee_code" = '99349' WHERE "label" = 'Sud-Soudan';
UPDATE "country" SET "insee_code" = '99104' WHERE "label" = 'Suède';
UPDATE "country" SET "insee_code" = '99140' WHERE "label" = 'Suisse';
UPDATE "country" SET "insee_code" = '99437' WHERE "label" = 'Suriname';
UPDATE "country" SET "insee_code" = '99206' WHERE "label" = 'Syrie';
UPDATE "country" SET "insee_code" = '99259' WHERE "label" = 'Tajikistan';
UPDATE "country" SET "insee_code" = '99309' WHERE "label" = 'Tanzanie';
UPDATE "country" SET "insee_code" = '99344' WHERE "label" = 'Tchad';
UPDATE "country" SET "insee_code" = '99219' WHERE "label" = 'Thaïlande';
UPDATE "country" SET "insee_code" = '99262' WHERE "label" = 'Timor-Leste';
UPDATE "country" SET "insee_code" = '99345' WHERE "label" = 'Togo';
UPDATE "country" SET "insee_code" = '99509' WHERE "label" = 'Tonga';
UPDATE "country" SET "insee_code" = '99433' WHERE "label" = 'Trinité-et-Tobago';
UPDATE "country" SET "insee_code" = '99351' WHERE "label" = 'Tunisie';
UPDATE "country" SET "insee_code" = '99260' WHERE "label" = 'Turkménistan';
UPDATE "country" SET "insee_code" = '99208' WHERE "label" = 'Turquie';
UPDATE "country" SET "insee_code" = '99511' WHERE "label" = 'Tuvalu';
UPDATE "country" SET "insee_code" = '99155' WHERE "label" = 'Ukraine';
UPDATE "country" SET "insee_code" = '99423' WHERE "label" = 'Uruguay';
UPDATE "country" SET "insee_code" = '99514' WHERE "label" = 'Vanuatu';
UPDATE "country" SET "insee_code" = '99424' WHERE "label" = 'Venezuela';
UPDATE "country" SET "insee_code" = '99243' WHERE "label" = 'Vietnam';
UPDATE "country" SET "insee_code" = '99251' WHERE "label" = 'Yémen';
UPDATE "country" SET "insee_code" = '99346' WHERE "label" = 'Zambie';
UPDATE "country" SET "insee_code" = '99310' WHERE "label" = 'Zimbabwe';

-- AlterTable: make insee_code required now that all rows are populated
ALTER TABLE "country" ALTER COLUMN "insee_code" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "country_insee_code_key" ON "country"("insee_code");
