-- AlterTable
ALTER TABLE "country" ADD COLUMN     "iso_code" VARCHAR(3);

-- Populate iso_code column with 3-letter ISO codes
UPDATE "country" SET "iso_code" = 'AFG' WHERE "label" = 'Afghanistan';
UPDATE "country" SET "iso_code" = 'ZAF' WHERE "label" = 'Afrique du Sud';
UPDATE "country" SET "iso_code" = 'ALB' WHERE "label" = 'Albanie';
UPDATE "country" SET "iso_code" = 'DZA' WHERE "label" = 'Algérie';
UPDATE "country" SET "iso_code" = 'DEU' WHERE "label" = 'Allemagne';
UPDATE "country" SET "iso_code" = 'AND' WHERE "label" = 'Andorre';
UPDATE "country" SET "iso_code" = 'AGO' WHERE "label" = 'Angola';
UPDATE "country" SET "iso_code" = 'ATG' WHERE "label" = 'Antigua-et-Barbuda';
UPDATE "country" SET "iso_code" = 'SAU' WHERE "label" = 'Arabie Saoudite';
UPDATE "country" SET "iso_code" = 'ARG' WHERE "label" = 'Argentine';
UPDATE "country" SET "iso_code" = 'ARM' WHERE "label" = 'Arménie';
UPDATE "country" SET "iso_code" = 'AUS' WHERE "label" = 'Australie';
UPDATE "country" SET "iso_code" = 'AUT' WHERE "label" = 'Autriche';
UPDATE "country" SET "iso_code" = 'AZE' WHERE "label" = 'Azerbaïdjan';
UPDATE "country" SET "iso_code" = 'BHS' WHERE "label" = 'Bahamas';
UPDATE "country" SET "iso_code" = 'BHR' WHERE "label" = 'Bahreïn';
UPDATE "country" SET "iso_code" = 'BGD' WHERE "label" = 'Bangladesh';
UPDATE "country" SET "iso_code" = 'BRB' WHERE "label" = 'Barbade';
UPDATE "country" SET "iso_code" = 'BEL' WHERE "label" = 'Belgique';
UPDATE "country" SET "iso_code" = 'BLZ' WHERE "label" = 'Belize';
UPDATE "country" SET "iso_code" = 'BEN' WHERE "label" = 'Bénin';
UPDATE "country" SET "iso_code" = 'BTN' WHERE "label" = 'Bhoutan';
UPDATE "country" SET "iso_code" = 'BLR' WHERE "label" = 'Biélorussie';
UPDATE "country" SET "iso_code" = 'BOL' WHERE "label" = 'Bolivie';
UPDATE "country" SET "iso_code" = 'BIH' WHERE "label" = 'Bosnie-Herzégovine';
UPDATE "country" SET "iso_code" = 'BWA' WHERE "label" = 'Botswana';
UPDATE "country" SET "iso_code" = 'BRA' WHERE "label" = 'Brésil';
UPDATE "country" SET "iso_code" = 'BRN' WHERE "label" = 'Brunei';
UPDATE "country" SET "iso_code" = 'BGR' WHERE "label" = 'Bulgarie';
UPDATE "country" SET "iso_code" = 'BFA' WHERE "label" = 'Burkina Faso';
UPDATE "country" SET "iso_code" = 'BDI' WHERE "label" = 'Burundi';
UPDATE "country" SET "iso_code" = 'CPV' WHERE "label" = 'Cabo Verde';
UPDATE "country" SET "iso_code" = 'KHM' WHERE "label" = 'Cambodge';
UPDATE "country" SET "iso_code" = 'CMR' WHERE "label" = 'Cameroun';
UPDATE "country" SET "iso_code" = 'CAN' WHERE "label" = 'Canada';
UPDATE "country" SET "iso_code" = 'CHL' WHERE "label" = 'Chili';
UPDATE "country" SET "iso_code" = 'CHN' WHERE "label" = 'Chine';
UPDATE "country" SET "iso_code" = 'CYP' WHERE "label" = 'Chypre';
UPDATE "country" SET "iso_code" = 'VAT' WHERE "label" = 'Cité du Vatican';
UPDATE "country" SET "iso_code" = 'COL' WHERE "label" = 'Colombie';
UPDATE "country" SET "iso_code" = 'COM' WHERE "label" = 'Comores';
UPDATE "country" SET "iso_code" = 'COG' WHERE "label" = 'Congo (Congo-Brazzaville)';
UPDATE "country" SET "iso_code" = 'PRK' WHERE "label" = 'Corée du Nord';
UPDATE "country" SET "iso_code" = 'KOR' WHERE "label" = 'Corée du Sud';
UPDATE "country" SET "iso_code" = 'CRI' WHERE "label" = 'Costa Rica';
UPDATE "country" SET "iso_code" = 'CIV' WHERE "label" = 'Côte d''Ivoire';
UPDATE "country" SET "iso_code" = 'HRV' WHERE "label" = 'Croatie';
UPDATE "country" SET "iso_code" = 'CUB' WHERE "label" = 'Cuba';
UPDATE "country" SET "iso_code" = 'DNK' WHERE "label" = 'Danemark';
UPDATE "country" SET "iso_code" = 'DJI' WHERE "label" = 'Djibouti';
UPDATE "country" SET "iso_code" = 'DMA' WHERE "label" = 'Dominique';
UPDATE "country" SET "iso_code" = 'EGY' WHERE "label" = 'Égypte';
UPDATE "country" SET "iso_code" = 'ARE' WHERE "label" = 'Émirats arabes unis';
UPDATE "country" SET "iso_code" = 'ECU' WHERE "label" = 'Équateur';
UPDATE "country" SET "iso_code" = 'ERI' WHERE "label" = 'Érythrée';
UPDATE "country" SET "iso_code" = 'ESP' WHERE "label" = 'Espagne';
UPDATE "country" SET "iso_code" = 'EST' WHERE "label" = 'Estonie';
UPDATE "country" SET "iso_code" = 'USA' WHERE "label" = 'États-Unis';
UPDATE "country" SET "iso_code" = 'ETH' WHERE "label" = 'Éthiopie';
UPDATE "country" SET "iso_code" = 'FJI' WHERE "label" = 'Fidji';
UPDATE "country" SET "iso_code" = 'FIN' WHERE "label" = 'Finlande';
UPDATE "country" SET "iso_code" = 'FRA' WHERE "label" = 'France';
UPDATE "country" SET "iso_code" = 'GAB' WHERE "label" = 'Gabon';
UPDATE "country" SET "iso_code" = 'GMB' WHERE "label" = 'Gambie';
UPDATE "country" SET "iso_code" = 'GEO' WHERE "label" = 'Géorgie';
UPDATE "country" SET "iso_code" = 'GHA' WHERE "label" = 'Ghana';
UPDATE "country" SET "iso_code" = 'GRC' WHERE "label" = 'Grèce';
UPDATE "country" SET "iso_code" = 'GRD' WHERE "label" = 'Grenade';
UPDATE "country" SET "iso_code" = 'GTM' WHERE "label" = 'Guatemala';
UPDATE "country" SET "iso_code" = 'GIN' WHERE "label" = 'Guinée';
UPDATE "country" SET "iso_code" = 'GNB' WHERE "label" = 'Guinée-Bissau';
UPDATE "country" SET "iso_code" = 'GNQ' WHERE "label" = 'Guinée équatoriale';
UPDATE "country" SET "iso_code" = 'GUY' WHERE "label" = 'Guyane';
UPDATE "country" SET "iso_code" = 'HTI' WHERE "label" = 'Haïti';
UPDATE "country" SET "iso_code" = 'HND' WHERE "label" = 'Honduras';
UPDATE "country" SET "iso_code" = 'HUN' WHERE "label" = 'Hongrie';
UPDATE "country" SET "iso_code" = 'MHL' WHERE "label" = 'Îles Marshall';
UPDATE "country" SET "iso_code" = 'SLB' WHERE "label" = 'Îles Salomon';
UPDATE "country" SET "iso_code" = 'IND' WHERE "label" = 'Inde';
UPDATE "country" SET "iso_code" = 'IDN' WHERE "label" = 'Indonésie';
UPDATE "country" SET "iso_code" = 'IRQ' WHERE "label" = 'Irak';
UPDATE "country" SET "iso_code" = 'IRN' WHERE "label" = 'Iran';
UPDATE "country" SET "iso_code" = 'IRL' WHERE "label" = 'Irlande';
UPDATE "country" SET "iso_code" = 'ISL' WHERE "label" = 'Islande';
UPDATE "country" SET "iso_code" = 'ISR' WHERE "label" = 'Israël';
UPDATE "country" SET "iso_code" = 'ITA' WHERE "label" = 'Italie';
UPDATE "country" SET "iso_code" = 'JAM' WHERE "label" = 'Jamaïque';
UPDATE "country" SET "iso_code" = 'JPN' WHERE "label" = 'Japon';
UPDATE "country" SET "iso_code" = 'JOR' WHERE "label" = 'Jordanie';
UPDATE "country" SET "iso_code" = 'KAZ' WHERE "label" = 'Kazakhstan';
UPDATE "country" SET "iso_code" = 'KEN' WHERE "label" = 'Kenya';
UPDATE "country" SET "iso_code" = 'KGZ' WHERE "label" = 'Kirghizistan';
UPDATE "country" SET "iso_code" = 'KIR' WHERE "label" = 'Kiribati';
UPDATE "country" SET "iso_code" = 'XKX' WHERE "label" = 'Kosovo';
UPDATE "country" SET "iso_code" = 'KWT' WHERE "label" = 'Koweït';
UPDATE "country" SET "iso_code" = 'LAO' WHERE "label" = 'Laos';
UPDATE "country" SET "iso_code" = 'LSO' WHERE "label" = 'Lesotho';
UPDATE "country" SET "iso_code" = 'LVA' WHERE "label" = 'Lettonie';
UPDATE "country" SET "iso_code" = 'LBN' WHERE "label" = 'Liban';
UPDATE "country" SET "iso_code" = 'LBR' WHERE "label" = 'Liberia';
UPDATE "country" SET "iso_code" = 'LBY' WHERE "label" = 'Libye';
UPDATE "country" SET "iso_code" = 'LIE' WHERE "label" = 'Liechtenstein';
UPDATE "country" SET "iso_code" = 'LTU' WHERE "label" = 'Lituanie';
UPDATE "country" SET "iso_code" = 'LUX' WHERE "label" = 'Luxembourg';
UPDATE "country" SET "iso_code" = 'MKD' WHERE "label" = 'Macédoine du Nord';
UPDATE "country" SET "iso_code" = 'MDG' WHERE "label" = 'Madagascar';
UPDATE "country" SET "iso_code" = 'MYS' WHERE "label" = 'Malaisie';
UPDATE "country" SET "iso_code" = 'MWI' WHERE "label" = 'Malawi';
UPDATE "country" SET "iso_code" = 'MDV' WHERE "label" = 'Maldives';
UPDATE "country" SET "iso_code" = 'MLI' WHERE "label" = 'Mali';
UPDATE "country" SET "iso_code" = 'MLT' WHERE "label" = 'Malte';
UPDATE "country" SET "iso_code" = 'MAR' WHERE "label" = 'Maroc';
UPDATE "country" SET "iso_code" = 'MUS' WHERE "label" = 'Maurice';
UPDATE "country" SET "iso_code" = 'MRT' WHERE "label" = 'Mauritanie';
UPDATE "country" SET "iso_code" = 'MEX' WHERE "label" = 'Mexique';
UPDATE "country" SET "iso_code" = 'FSM' WHERE "label" = 'Micronésie';
UPDATE "country" SET "iso_code" = 'MDA' WHERE "label" = 'Moldavie';
UPDATE "country" SET "iso_code" = 'MCO' WHERE "label" = 'Monaco';
UPDATE "country" SET "iso_code" = 'MNG' WHERE "label" = 'Mongolie';
UPDATE "country" SET "iso_code" = 'MNE' WHERE "label" = 'Monténégro';
UPDATE "country" SET "iso_code" = 'MOZ' WHERE "label" = 'Mozambique';
UPDATE "country" SET "iso_code" = 'MMR' WHERE "label" = 'Myanmar (Birmanie)';
UPDATE "country" SET "iso_code" = 'NAM' WHERE "label" = 'Namibie';
UPDATE "country" SET "iso_code" = 'NRU' WHERE "label" = 'Nauru';
UPDATE "country" SET "iso_code" = 'NPL' WHERE "label" = 'Népal';
UPDATE "country" SET "iso_code" = 'NIC' WHERE "label" = 'Nicaragua';
UPDATE "country" SET "iso_code" = 'NER' WHERE "label" = 'Niger';
UPDATE "country" SET "iso_code" = 'NGA' WHERE "label" = 'Nigeria';
UPDATE "country" SET "iso_code" = 'NOR' WHERE "label" = 'Norvège';
UPDATE "country" SET "iso_code" = 'NZL' WHERE "label" = 'Nouvelle-Zélande';
UPDATE "country" SET "iso_code" = 'OMN' WHERE "label" = 'Oman';
UPDATE "country" SET "iso_code" = 'UGA' WHERE "label" = 'Ouganda';
UPDATE "country" SET "iso_code" = 'UZB' WHERE "label" = 'Ouzbékistan';
UPDATE "country" SET "iso_code" = 'PAK' WHERE "label" = 'Pakistan';
UPDATE "country" SET "iso_code" = 'PLW' WHERE "label" = 'Palaos';
UPDATE "country" SET "iso_code" = 'PSE' WHERE "label" = 'Palestine';
UPDATE "country" SET "iso_code" = 'PAN' WHERE "label" = 'Panama';
UPDATE "country" SET "iso_code" = 'PNG' WHERE "label" = 'Papouasie-Nouvelle-Guinée';
UPDATE "country" SET "iso_code" = 'PRY' WHERE "label" = 'Paraguay';
UPDATE "country" SET "iso_code" = 'NLD' WHERE "label" = 'Pays-Bas';
UPDATE "country" SET "iso_code" = 'PER' WHERE "label" = 'Pérou';
UPDATE "country" SET "iso_code" = 'PHL' WHERE "label" = 'Philippines';
UPDATE "country" SET "iso_code" = 'POL' WHERE "label" = 'Pologne';
UPDATE "country" SET "iso_code" = 'PRT' WHERE "label" = 'Portugal';
UPDATE "country" SET "iso_code" = 'QAT' WHERE "label" = 'Qatar';
UPDATE "country" SET "iso_code" = 'CAF' WHERE "label" = 'République centrafricaine';
UPDATE "country" SET "iso_code" = 'COD' WHERE "label" = 'République démocratique du Congo';
UPDATE "country" SET "iso_code" = 'DOM' WHERE "label" = 'République dominicaine';
UPDATE "country" SET "iso_code" = 'CZE' WHERE "label" = 'République tchèque (Tchéquie)';
UPDATE "country" SET "iso_code" = 'ROU' WHERE "label" = 'Roumanie';
UPDATE "country" SET "iso_code" = 'GBR' WHERE "label" = 'Royaume-Uni';
UPDATE "country" SET "iso_code" = 'RUS' WHERE "label" = 'Russie';
UPDATE "country" SET "iso_code" = 'RWA' WHERE "label" = 'Rwanda';
UPDATE "country" SET "iso_code" = 'LCA' WHERE "label" = 'Sainte-Lucie';
UPDATE "country" SET "iso_code" = 'KNA' WHERE "label" = 'Saint-Kitts-et-Nevis';
UPDATE "country" SET "iso_code" = 'SMR' WHERE "label" = 'Saint-Marin';
UPDATE "country" SET "iso_code" = 'VCT' WHERE "label" = 'Saint-Vincent-et-les Grenadines';
UPDATE "country" SET "iso_code" = 'SLV' WHERE "label" = 'Salvador';
UPDATE "country" SET "iso_code" = 'WSM' WHERE "label" = 'Samoa';
UPDATE "country" SET "iso_code" = 'STP' WHERE "label" = 'Sao Tomé-et-Principe';
UPDATE "country" SET "iso_code" = 'SEN' WHERE "label" = 'Sénégal';
UPDATE "country" SET "iso_code" = 'SRB' WHERE "label" = 'Serbie';
UPDATE "country" SET "iso_code" = 'SYC' WHERE "label" = 'Seychelles';
UPDATE "country" SET "iso_code" = 'SLE' WHERE "label" = 'Sierra Leone';
UPDATE "country" SET "iso_code" = 'SGP' WHERE "label" = 'Singapour';
UPDATE "country" SET "iso_code" = 'SVK' WHERE "label" = 'Slovaquie';
UPDATE "country" SET "iso_code" = 'SVN' WHERE "label" = 'Slovénie';
UPDATE "country" SET "iso_code" = 'SOM' WHERE "label" = 'Somalie';
UPDATE "country" SET "iso_code" = 'SDN' WHERE "label" = 'Soudan';
UPDATE "country" SET "iso_code" = 'LKA' WHERE "label" = 'Sri Lanka';
UPDATE "country" SET "iso_code" = 'SSD' WHERE "label" = 'Sud-Soudan';
UPDATE "country" SET "iso_code" = 'SWE' WHERE "label" = 'Suède';
UPDATE "country" SET "iso_code" = 'CHE' WHERE "label" = 'Suisse';
UPDATE "country" SET "iso_code" = 'SUR' WHERE "label" = 'Suriname';
UPDATE "country" SET "iso_code" = 'SYR' WHERE "label" = 'Syrie';
UPDATE "country" SET "iso_code" = 'TJK' WHERE "label" = 'Tajikistan';
UPDATE "country" SET "iso_code" = 'TZA' WHERE "label" = 'Tanzanie';
UPDATE "country" SET "iso_code" = 'TCD' WHERE "label" = 'Tchad';
UPDATE "country" SET "iso_code" = 'THA' WHERE "label" = 'Thaïlande';
UPDATE "country" SET "iso_code" = 'TLS' WHERE "label" = 'Timor-Leste';
UPDATE "country" SET "iso_code" = 'TGO' WHERE "label" = 'Togo';
UPDATE "country" SET "iso_code" = 'TON' WHERE "label" = 'Tonga';
UPDATE "country" SET "iso_code" = 'TTO' WHERE "label" = 'Trinité-et-Tobago';
UPDATE "country" SET "iso_code" = 'TUN' WHERE "label" = 'Tunisie';
UPDATE "country" SET "iso_code" = 'TKM' WHERE "label" = 'Turkménistan';
UPDATE "country" SET "iso_code" = 'TUR' WHERE "label" = 'Turquie';
UPDATE "country" SET "iso_code" = 'TUV' WHERE "label" = 'Tuvalu';
UPDATE "country" SET "iso_code" = 'UKR' WHERE "label" = 'Ukraine';
UPDATE "country" SET "iso_code" = 'URY' WHERE "label" = 'Uruguay';
UPDATE "country" SET "iso_code" = 'VUT' WHERE "label" = 'Vanuatu';
UPDATE "country" SET "iso_code" = 'VEN' WHERE "label" = 'Venezuela';
UPDATE "country" SET "iso_code" = 'VNM' WHERE "label" = 'Vietnam';
UPDATE "country" SET "iso_code" = 'YEM' WHERE "label" = 'Yémen';
UPDATE "country" SET "iso_code" = 'ZMB' WHERE "label" = 'Zambie';
UPDATE "country" SET "iso_code" = 'ZWE' WHERE "label" = 'Zimbabwe';

-- Add NOT NULL constraint to iso_code column
ALTER TABLE "country" ALTER COLUMN "iso_code" SET NOT NULL;
ALTER TABLE "country" ADD CONSTRAINT "country_iso_code_key" UNIQUE ("iso_code");