-- AlterTable: add column as nullable so existing rows can be updated
ALTER TABLE "country" ADD COLUMN "nationality" VARCHAR(255);

-- Populate nationality for each country (féminin)
UPDATE "country" SET "nationality" = 'Afghane' WHERE "label" = 'Afghanistan';
UPDATE "country" SET "nationality" = 'Sud-Africaine' WHERE "label" = 'Afrique du Sud';
UPDATE "country" SET "nationality" = 'Albanaise' WHERE "label" = 'Albanie';
UPDATE "country" SET "nationality" = 'Algérienne' WHERE "label" = 'Algérie';
UPDATE "country" SET "nationality" = 'Allemande' WHERE "label" = 'Allemagne';
UPDATE "country" SET "nationality" = 'Andorrane' WHERE "label" = 'Andorre';
UPDATE "country" SET "nationality" = 'Angolaise' WHERE "label" = 'Angola';
UPDATE "country" SET "nationality" = 'Antiguaise-et-Barbudienne' WHERE "label" = 'Antigua-et-Barbuda';
UPDATE "country" SET "nationality" = 'Saoudienne' WHERE "label" = 'Arabie Saoudite';
UPDATE "country" SET "nationality" = 'Argentine' WHERE "label" = 'Argentine';
UPDATE "country" SET "nationality" = 'Arménienne' WHERE "label" = 'Arménie';
UPDATE "country" SET "nationality" = 'Australienne' WHERE "label" = 'Australie';
UPDATE "country" SET "nationality" = 'Autrichienne' WHERE "label" = 'Autriche';
UPDATE "country" SET "nationality" = 'Azerbaïdjanaise' WHERE "label" = 'Azerbaïdjan';
UPDATE "country" SET "nationality" = 'Bahaméenne' WHERE "label" = 'Bahamas';
UPDATE "country" SET "nationality" = 'Bahreïnienne' WHERE "label" = 'Bahreïn';
UPDATE "country" SET "nationality" = 'Bangladaise' WHERE "label" = 'Bangladesh';
UPDATE "country" SET "nationality" = 'Barbadienne' WHERE "label" = 'Barbade';
UPDATE "country" SET "nationality" = 'Belge' WHERE "label" = 'Belgique';
UPDATE "country" SET "nationality" = 'Bélizienne' WHERE "label" = 'Belize';
UPDATE "country" SET "nationality" = 'Bhoutanaise' WHERE "label" = 'Bhoutan';
UPDATE "country" SET "nationality" = 'Biélorusse' WHERE "label" = 'Biélorussie';
UPDATE "country" SET "nationality" = 'Bolivienne' WHERE "label" = 'Bolivie';
UPDATE "country" SET "nationality" = 'Bosnienne' WHERE "label" = 'Bosnie-Herzégovine';
UPDATE "country" SET "nationality" = 'Botswanaise' WHERE "label" = 'Botswana';
UPDATE "country" SET "nationality" = 'Brunéienne' WHERE "label" = 'Brunei';
UPDATE "country" SET "nationality" = 'Brésilienne' WHERE "label" = 'Brésil';
UPDATE "country" SET "nationality" = 'Bulgare' WHERE "label" = 'Bulgarie';
UPDATE "country" SET "nationality" = 'Burkinabée' WHERE "label" = 'Burkina Faso';
UPDATE "country" SET "nationality" = 'Burundaise' WHERE "label" = 'Burundi';
UPDATE "country" SET "nationality" = 'Béninoise' WHERE "label" = 'Bénin';
UPDATE "country" SET "nationality" = 'Cap-Verdienne' WHERE "label" = 'Cabo Verde';
UPDATE "country" SET "nationality" = 'Cambodgienne' WHERE "label" = 'Cambodge';
UPDATE "country" SET "nationality" = 'Camerounaise' WHERE "label" = 'Cameroun';
UPDATE "country" SET "nationality" = 'Canadienne' WHERE "label" = 'Canada';
UPDATE "country" SET "nationality" = 'Chilienne' WHERE "label" = 'Chili';
UPDATE "country" SET "nationality" = 'Chinoise' WHERE "label" = 'Chine';
UPDATE "country" SET "nationality" = 'Chypriote' WHERE "label" = 'Chypre';
UPDATE "country" SET "nationality" = 'Vaticane' WHERE "label" = 'Cité du Vatican';
UPDATE "country" SET "nationality" = 'Colombienne' WHERE "label" = 'Colombie';
UPDATE "country" SET "nationality" = 'Comorienne' WHERE "label" = 'Comores';
UPDATE "country" SET "nationality" = 'Congolaise' WHERE "label" = 'Congo (Congo-Brazzaville)';
UPDATE "country" SET "nationality" = 'Nord-Coréenne' WHERE "label" = 'Corée du Nord';
UPDATE "country" SET "nationality" = 'Sud-Coréenne' WHERE "label" = 'Corée du Sud';
UPDATE "country" SET "nationality" = 'Costaricienne' WHERE "label" = 'Costa Rica';
UPDATE "country" SET "nationality" = 'Croate' WHERE "label" = 'Croatie';
UPDATE "country" SET "nationality" = 'Cubaine' WHERE "label" = 'Cuba';
UPDATE "country" SET "nationality" = 'Ivoirienne' WHERE "label" = 'Côte d''Ivoire';
UPDATE "country" SET "nationality" = 'Danoise' WHERE "label" = 'Danemark';
UPDATE "country" SET "nationality" = 'Djiboutienne' WHERE "label" = 'Djibouti';
UPDATE "country" SET "nationality" = 'Dominiquaise' WHERE "label" = 'Dominique';
UPDATE "country" SET "nationality" = 'Espagnole' WHERE "label" = 'Espagne';
UPDATE "country" SET "nationality" = 'Estonienne' WHERE "label" = 'Estonie';
UPDATE "country" SET "nationality" = 'Fidjienne' WHERE "label" = 'Fidji';
UPDATE "country" SET "nationality" = 'Finlandaise' WHERE "label" = 'Finlande';
UPDATE "country" SET "nationality" = 'Française' WHERE "label" = 'France';
UPDATE "country" SET "nationality" = 'Gabonaise' WHERE "label" = 'Gabon';
UPDATE "country" SET "nationality" = 'Gambienne' WHERE "label" = 'Gambie';
UPDATE "country" SET "nationality" = 'Ghanéenne' WHERE "label" = 'Ghana';
UPDATE "country" SET "nationality" = 'Grenadienne' WHERE "label" = 'Grenade';
UPDATE "country" SET "nationality" = 'Grecque' WHERE "label" = 'Grèce';
UPDATE "country" SET "nationality" = 'Guatémaltèque' WHERE "label" = 'Guatemala';
UPDATE "country" SET "nationality" = 'Guinéenne' WHERE "label" = 'Guinée';
UPDATE "country" SET "nationality" = 'Équato-Guinéenne' WHERE "label" = 'Guinée équatoriale';
UPDATE "country" SET "nationality" = 'Bissau-Guinéenne' WHERE "label" = 'Guinée-Bissau';
UPDATE "country" SET "nationality" = 'Guyanaise' WHERE "label" = 'Guyane';
UPDATE "country" SET "nationality" = 'Géorgienne' WHERE "label" = 'Géorgie';
UPDATE "country" SET "nationality" = 'Haïtienne' WHERE "label" = 'Haïti';
UPDATE "country" SET "nationality" = 'Hondurienne' WHERE "label" = 'Honduras';
UPDATE "country" SET "nationality" = 'Hongroise' WHERE "label" = 'Hongrie';
UPDATE "country" SET "nationality" = 'Indienne' WHERE "label" = 'Inde';
UPDATE "country" SET "nationality" = 'Indonésienne' WHERE "label" = 'Indonésie';
UPDATE "country" SET "nationality" = 'Irakienne' WHERE "label" = 'Irak';
UPDATE "country" SET "nationality" = 'Iranienne' WHERE "label" = 'Iran';
UPDATE "country" SET "nationality" = 'Irlandaise' WHERE "label" = 'Irlande';
UPDATE "country" SET "nationality" = 'Islandaise' WHERE "label" = 'Islande';
UPDATE "country" SET "nationality" = 'Israélienne' WHERE "label" = 'Israël';
UPDATE "country" SET "nationality" = 'Italienne' WHERE "label" = 'Italie';
UPDATE "country" SET "nationality" = 'Jamaïcaine' WHERE "label" = 'Jamaïque';
UPDATE "country" SET "nationality" = 'Japonaise' WHERE "label" = 'Japon';
UPDATE "country" SET "nationality" = 'Jordanienne' WHERE "label" = 'Jordanie';
UPDATE "country" SET "nationality" = 'Kazakhstanaise' WHERE "label" = 'Kazakhstan';
UPDATE "country" SET "nationality" = 'Kényane' WHERE "label" = 'Kenya';
UPDATE "country" SET "nationality" = 'Kirghize' WHERE "label" = 'Kirghizistan';
UPDATE "country" SET "nationality" = 'Kiribatienne' WHERE "label" = 'Kiribati';
UPDATE "country" SET "nationality" = 'Kosovare' WHERE "label" = 'Kosovo';
UPDATE "country" SET "nationality" = 'Koweïtienne' WHERE "label" = 'Koweït';
UPDATE "country" SET "nationality" = 'Laotienne' WHERE "label" = 'Laos';
UPDATE "country" SET "nationality" = 'Lesothane' WHERE "label" = 'Lesotho';
UPDATE "country" SET "nationality" = 'Lettone' WHERE "label" = 'Lettonie';
UPDATE "country" SET "nationality" = 'Libanaise' WHERE "label" = 'Liban';
UPDATE "country" SET "nationality" = 'Libérienne' WHERE "label" = 'Liberia';
UPDATE "country" SET "nationality" = 'Libyenne' WHERE "label" = 'Libye';
UPDATE "country" SET "nationality" = 'Liechtensteinoise' WHERE "label" = 'Liechtenstein';
UPDATE "country" SET "nationality" = 'Lituanienne' WHERE "label" = 'Lituanie';
UPDATE "country" SET "nationality" = 'Luxembourgeoise' WHERE "label" = 'Luxembourg';
UPDATE "country" SET "nationality" = 'Macédonienne' WHERE "label" = 'Macédoine du Nord';
UPDATE "country" SET "nationality" = 'Malgache' WHERE "label" = 'Madagascar';
UPDATE "country" SET "nationality" = 'Malaisienne' WHERE "label" = 'Malaisie';
UPDATE "country" SET "nationality" = 'Malawienne' WHERE "label" = 'Malawi';
UPDATE "country" SET "nationality" = 'Maldivienne' WHERE "label" = 'Maldives';
UPDATE "country" SET "nationality" = 'Malienne' WHERE "label" = 'Mali';
UPDATE "country" SET "nationality" = 'Maltaise' WHERE "label" = 'Malte';
UPDATE "country" SET "nationality" = 'Marocaine' WHERE "label" = 'Maroc';
UPDATE "country" SET "nationality" = 'Mauricienne' WHERE "label" = 'Maurice';
UPDATE "country" SET "nationality" = 'Mauritanienne' WHERE "label" = 'Mauritanie';
UPDATE "country" SET "nationality" = 'Mexicaine' WHERE "label" = 'Mexique';
UPDATE "country" SET "nationality" = 'Micronésienne' WHERE "label" = 'Micronésie';
UPDATE "country" SET "nationality" = 'Moldave' WHERE "label" = 'Moldavie';
UPDATE "country" SET "nationality" = 'Monégasque' WHERE "label" = 'Monaco';
UPDATE "country" SET "nationality" = 'Mongole' WHERE "label" = 'Mongolie';
UPDATE "country" SET "nationality" = 'Monténégrine' WHERE "label" = 'Monténégro';
UPDATE "country" SET "nationality" = 'Mozambicaine' WHERE "label" = 'Mozambique';
UPDATE "country" SET "nationality" = 'Birmane' WHERE "label" = 'Myanmar (Birmanie)';
UPDATE "country" SET "nationality" = 'Namibienne' WHERE "label" = 'Namibie';
UPDATE "country" SET "nationality" = 'Nauruane' WHERE "label" = 'Nauru';
UPDATE "country" SET "nationality" = 'Nicaraguayenne' WHERE "label" = 'Nicaragua';
UPDATE "country" SET "nationality" = 'Nigérienne' WHERE "label" = 'Niger';
UPDATE "country" SET "nationality" = 'Nigériane' WHERE "label" = 'Nigeria';
UPDATE "country" SET "nationality" = 'Norvégienne' WHERE "label" = 'Norvège';
UPDATE "country" SET "nationality" = 'Néo-Zélandaise' WHERE "label" = 'Nouvelle-Zélande';
UPDATE "country" SET "nationality" = 'Népalaise' WHERE "label" = 'Népal';
UPDATE "country" SET "nationality" = 'Omanaise' WHERE "label" = 'Oman';
UPDATE "country" SET "nationality" = 'Ougandaise' WHERE "label" = 'Ouganda';
UPDATE "country" SET "nationality" = 'Ouzbèke' WHERE "label" = 'Ouzbékistan';
UPDATE "country" SET "nationality" = 'Pakistanaise' WHERE "label" = 'Pakistan';
UPDATE "country" SET "nationality" = 'Palaosienne' WHERE "label" = 'Palaos';
UPDATE "country" SET "nationality" = 'Palestinienne' WHERE "label" = 'Palestine';
UPDATE "country" SET "nationality" = 'Panaméenne' WHERE "label" = 'Panama';
UPDATE "country" SET "nationality" = 'Papouasienne' WHERE "label" = 'Papouasie-Nouvelle-Guinée';
UPDATE "country" SET "nationality" = 'Paraguayenne' WHERE "label" = 'Paraguay';
UPDATE "country" SET "nationality" = 'Néerlandaise' WHERE "label" = 'Pays-Bas';
UPDATE "country" SET "nationality" = 'Philippinoise' WHERE "label" = 'Philippines';
UPDATE "country" SET "nationality" = 'Polonaise' WHERE "label" = 'Pologne';
UPDATE "country" SET "nationality" = 'Portugaise' WHERE "label" = 'Portugal';
UPDATE "country" SET "nationality" = 'Péruvienne' WHERE "label" = 'Pérou';
UPDATE "country" SET "nationality" = 'Qatarienne' WHERE "label" = 'Qatar';
UPDATE "country" SET "nationality" = 'Roumaine' WHERE "label" = 'Roumanie';
UPDATE "country" SET "nationality" = 'Britannique' WHERE "label" = 'Royaume-Uni';
UPDATE "country" SET "nationality" = 'Russe' WHERE "label" = 'Russie';
UPDATE "country" SET "nationality" = 'Rwandaise' WHERE "label" = 'Rwanda';
UPDATE "country" SET "nationality" = 'Centrafricaine' WHERE "label" = 'République centrafricaine';
UPDATE "country" SET "nationality" = 'Dominicaine' WHERE "label" = 'République dominicaine';
UPDATE "country" SET "nationality" = 'Congolaise' WHERE "label" = 'République démocratique du Congo';
UPDATE "country" SET "nationality" = 'Tchèque' WHERE "label" = 'République tchèque (Tchéquie)';
UPDATE "country" SET "nationality" = 'Kittitienne' WHERE "label" = 'Saint-Kitts-et-Nevis';
UPDATE "country" SET "nationality" = 'Sanmarinoise' WHERE "label" = 'Saint-Marin';
UPDATE "country" SET "nationality" = 'Vincentaise' WHERE "label" = 'Saint-Vincent-et-les Grenadines';
UPDATE "country" SET "nationality" = 'Sainte-Lucienne' WHERE "label" = 'Sainte-Lucie';
UPDATE "country" SET "nationality" = 'Salvadorienne' WHERE "label" = 'Salvador';
UPDATE "country" SET "nationality" = 'Samoane' WHERE "label" = 'Samoa';
UPDATE "country" SET "nationality" = 'Santoméenne' WHERE "label" = 'Sao Tomé-et-Principe';
UPDATE "country" SET "nationality" = 'Serbe' WHERE "label" = 'Serbie';
UPDATE "country" SET "nationality" = 'Seychelloise' WHERE "label" = 'Seychelles';
UPDATE "country" SET "nationality" = 'Sierra-Léonaise' WHERE "label" = 'Sierra Leone';
UPDATE "country" SET "nationality" = 'Singapourienne' WHERE "label" = 'Singapour';
UPDATE "country" SET "nationality" = 'Slovaque' WHERE "label" = 'Slovaquie';
UPDATE "country" SET "nationality" = 'Slovène' WHERE "label" = 'Slovénie';
UPDATE "country" SET "nationality" = 'Somalienne' WHERE "label" = 'Somalie';
UPDATE "country" SET "nationality" = 'Soudanaise' WHERE "label" = 'Soudan';
UPDATE "country" SET "nationality" = 'Sri-Lankaise' WHERE "label" = 'Sri Lanka';
UPDATE "country" SET "nationality" = 'Sud-Soudanaise' WHERE "label" = 'Sud-Soudan';
UPDATE "country" SET "nationality" = 'Suisse' WHERE "label" = 'Suisse';
UPDATE "country" SET "nationality" = 'Surinamaise' WHERE "label" = 'Suriname';
UPDATE "country" SET "nationality" = 'Suédoise' WHERE "label" = 'Suède';
UPDATE "country" SET "nationality" = 'Syrienne' WHERE "label" = 'Syrie';
UPDATE "country" SET "nationality" = 'Sénégalaise' WHERE "label" = 'Sénégal';
UPDATE "country" SET "nationality" = 'Tadjike' WHERE "label" = 'Tajikistan';
UPDATE "country" SET "nationality" = 'Tanzanienne' WHERE "label" = 'Tanzanie';
UPDATE "country" SET "nationality" = 'Taïwanaise' WHERE "label" = 'Taïwan';
UPDATE "country" SET "nationality" = 'Tchadienne' WHERE "label" = 'Tchad';
UPDATE "country" SET "nationality" = 'Thaïlandaise' WHERE "label" = 'Thaïlande';
UPDATE "country" SET "nationality" = 'Est-Timoraise' WHERE "label" = 'Timor-Leste';
UPDATE "country" SET "nationality" = 'Togolaise' WHERE "label" = 'Togo';
UPDATE "country" SET "nationality" = 'Tonguienne' WHERE "label" = 'Tonga';
UPDATE "country" SET "nationality" = 'Trinidadienne' WHERE "label" = 'Trinité-et-Tobago';
UPDATE "country" SET "nationality" = 'Tunisienne' WHERE "label" = 'Tunisie';
UPDATE "country" SET "nationality" = 'Turkmène' WHERE "label" = 'Turkménistan';
UPDATE "country" SET "nationality" = 'Turque' WHERE "label" = 'Turquie';
UPDATE "country" SET "nationality" = 'Tuvaluane' WHERE "label" = 'Tuvalu';
UPDATE "country" SET "nationality" = 'Ukrainienne' WHERE "label" = 'Ukraine';
UPDATE "country" SET "nationality" = 'Uruguayenne' WHERE "label" = 'Uruguay';
UPDATE "country" SET "nationality" = 'Vanuataise' WHERE "label" = 'Vanuatu';
UPDATE "country" SET "nationality" = 'Vénézuélienne' WHERE "label" = 'Venezuela';
UPDATE "country" SET "nationality" = 'Vietnamienne' WHERE "label" = 'Vietnam';
UPDATE "country" SET "nationality" = 'Yéménite' WHERE "label" = 'Yémen';
UPDATE "country" SET "nationality" = 'Zambienne' WHERE "label" = 'Zambie';
UPDATE "country" SET "nationality" = 'Zimbabwéenne' WHERE "label" = 'Zimbabwe';
UPDATE "country" SET "nationality" = 'Égyptienne' WHERE "label" = 'Égypte';
UPDATE "country" SET "nationality" = 'Émiratie' WHERE "label" = 'Émirats arabes unis';
UPDATE "country" SET "nationality" = 'Équatorienne' WHERE "label" = 'Équateur';
UPDATE "country" SET "nationality" = 'Érythréenne' WHERE "label" = 'Érythrée';
UPDATE "country" SET "nationality" = 'Américaine' WHERE "label" = 'États-Unis';
UPDATE "country" SET "nationality" = 'Éthiopienne' WHERE "label" = 'Éthiopie';
UPDATE "country" SET "nationality" = 'Marshallaise' WHERE "label" = 'Îles Marshall';
UPDATE "country" SET "nationality" = 'Salomonaise' WHERE "label" = 'Îles Salomon';

-- Make country.nationality NOT NULL after all rows are populated
ALTER TABLE "country" ALTER COLUMN "nationality" SET NOT NULL;

-- Add nationality column to candidate_info_france_connect
ALTER TABLE "candidate_info_france_connect" ADD COLUMN "nationality" VARCHAR(255);

-- Populate nationality from existing country relation
UPDATE "candidate_info_france_connect" AS cifc
SET "nationality" = c."nationality"
FROM "country" c
WHERE cifc.country_id = c.id;
