import { PrismaClient } from "@prisma/client";

const departments = [
  {
    label: "Ain",
    code: "01",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Aisne",
    code: "02",
    codeRegion: "32",
    timezone: "Europe/Paris",
  },
  {
    label: "Allier",
    code: "03",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Alpes-de-Haute-Provence",
    code: "04",
    codeRegion: "93",
    timezone: "Europe/Paris",
  },
  {
    label: "Hautes-Alpes",
    code: "05",
    codeRegion: "93",
    timezone: "Europe/Paris",
  },
  {
    label: "Alpes-Maritimes",
    code: "06",
    codeRegion: "93",
    timezone: "Europe/Paris",
  },
  {
    label: "Ardèche",
    code: "07",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Ardennes",
    code: "08",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Ariège",
    code: "09",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Aube",
    code: "10",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Aude",
    code: "11",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Aveyron",
    code: "12",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Bouches-du-Rhône",
    code: "13",
    codeRegion: "93",
    timezone: "Europe/Paris",
  },
  {
    label: "Calvados",
    code: "14",
    codeRegion: "28",
    timezone: "Europe/Paris",
  },
  {
    label: "Cantal",
    code: "15",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Charente",
    code: "16",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Charente-Maritime",
    code: "17",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Cher",
    code: "18",
    codeRegion: "24",
    timezone: "Europe/Paris",
  },
  {
    label: "Corrèze",
    code: "19",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Côte-d'Or",
    code: "21",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Côtes-d'Armor",
    code: "22",
    codeRegion: "53",
    timezone: "Europe/Paris",
  },
  {
    label: "Creuse",
    code: "23",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Dordogne",
    code: "24",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Doubs",
    code: "25",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Drôme",
    code: "26",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Eure",
    code: "27",
    codeRegion: "28",
    timezone: "Europe/Paris",
  },
  {
    label: "Eure-et-Loir",
    code: "28",
    codeRegion: "24",
    timezone: "Europe/Paris",
  },
  {
    label: "Finistère",
    code: "29",
    codeRegion: "53",
    timezone: "Europe/Paris",
  },
  {
    label: "Corse-du-Sud",
    code: "2A",
    codeRegion: "94",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Corse",
    code: "2B",
    codeRegion: "94",
    timezone: "Europe/Paris",
  },
  {
    label: "Gard",
    code: "30",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Garonne",
    code: "31",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Gers",
    code: "32",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Gironde",
    code: "33",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Hérault",
    code: "34",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Ille-et-Vilaine",
    code: "35",
    codeRegion: "53",
    timezone: "Europe/Paris",
  },
  {
    label: "Indre",
    code: "36",
    codeRegion: "24",
    timezone: "Europe/Paris",
  },
  {
    label: "Indre-et-Loire",
    code: "37",
    codeRegion: "24",
    timezone: "Europe/Paris",
  },
  {
    label: "Isère",
    code: "38",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Jura",
    code: "39",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Landes",
    code: "40",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Loir-et-Cher",
    code: "41",
    codeRegion: "24",
    timezone: "Europe/Paris",
  },
  {
    label: "Loire",
    code: "42",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Loire",
    code: "43",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Loire-Atlantique",
    code: "44",
    codeRegion: "52",
    timezone: "Europe/Paris",
  },
  {
    label: "Loiret",
    code: "45",
    codeRegion: "24",
    timezone: "Europe/Paris",
  },
  {
    label: "Lot",
    code: "46",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Lot-et-Garonne",
    code: "47",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Lozère",
    code: "48",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Maine-et-Loire",
    code: "49",
    codeRegion: "52",
    timezone: "Europe/Paris",
  },
  {
    label: "Manche",
    code: "50",
    codeRegion: "28",
    timezone: "Europe/Paris",
  },
  {
    label: "Marne",
    code: "51",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Marne",
    code: "52",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Mayenne",
    code: "53",
    codeRegion: "52",
    timezone: "Europe/Paris",
  },
  {
    label: "Meurthe-et-Moselle",
    code: "54",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Meuse",
    code: "55",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Morbihan",
    code: "56",
    codeRegion: "53",
    timezone: "Europe/Paris",
  },
  {
    label: "Moselle",
    code: "57",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Nièvre",
    code: "58",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Nord",
    code: "59",
    codeRegion: "32",
    timezone: "Europe/Paris",
  },
  {
    label: "Oise",
    code: "60",
    codeRegion: "32",
    timezone: "Europe/Paris",
  },
  {
    label: "Orne",
    code: "61",
    codeRegion: "28",
    timezone: "Europe/Paris",
  },
  {
    label: "Pas-de-Calais",
    code: "62",
    codeRegion: "32",
    timezone: "Europe/Paris",
  },
  {
    label: "Puy-de-Dôme",
    code: "63",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Pyrénées-Atlantiques",
    code: "64",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Hautes-Pyrénées",
    code: "65",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Pyrénées-Orientales",
    code: "66",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Bas-Rhin",
    code: "67",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Haut-Rhin",
    code: "68",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Rhône",
    code: "69",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Saône",
    code: "70",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Saône-et-Loire",
    code: "71",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Sarthe",
    code: "72",
    codeRegion: "52",
    timezone: "Europe/Paris",
  },
  {
    label: "Savoie",
    code: "73",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Savoie",
    code: "74",
    codeRegion: "84",
    timezone: "Europe/Paris",
  },
  {
    label: "Paris",
    code: "75",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Seine-Maritime",
    code: "76",
    codeRegion: "28",
    timezone: "Europe/Paris",
  },
  {
    label: "Seine-et-Marne",
    code: "77",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Yvelines",
    code: "78",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Deux-Sèvres",
    code: "79",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Somme",
    code: "80",
    codeRegion: "32",
    timezone: "Europe/Paris",
  },
  {
    label: "Tarn",
    code: "81",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Tarn-et-Garonne",
    code: "82",
    codeRegion: "76",
    timezone: "Europe/Paris",
  },
  {
    label: "Var",
    code: "83",
    codeRegion: "93",
    timezone: "Europe/Paris",
  },
  {
    label: "Vaucluse",
    code: "84",
    codeRegion: "93",
    timezone: "Europe/Paris",
  },
  {
    label: "Vendée",
    code: "85",
    codeRegion: "52",
    timezone: "Europe/Paris",
  },
  {
    label: "Vienne",
    code: "86",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Haute-Vienne",
    code: "87",
    codeRegion: "75",
    timezone: "Europe/Paris",
  },
  {
    label: "Vosges",
    code: "88",
    codeRegion: "44",
    timezone: "Europe/Paris",
  },
  {
    label: "Yonne",
    code: "89",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Territoire de Belfort",
    code: "90",
    codeRegion: "27",
    timezone: "Europe/Paris",
  },
  {
    label: "Essonne",
    code: "91",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Hauts-de-Seine",
    code: "92",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Seine-Saint-Denis",
    code: "93",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Val-de-Marne",
    code: "94",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Val-d'Oise",
    code: "95",
    codeRegion: "11",
    timezone: "Europe/Paris",
  },
  {
    label: "Guadeloupe",
    code: "971",
    codeRegion: "01",
    timezone: "America/Guadeloupe",
  },
  {
    label: "Saint-Martin",
    code: "97150",
    codeRegion: "07",
    timezone: "America/Marigot",
  },
  {
    label: "Martinique",
    code: "972",
    codeRegion: "02",
    timezone: "America/Martinique",
  },
  {
    label: "Guyane",
    code: "973",
    codeRegion: "03",
    timezone: "America/Cayenne",
  },
  {
    label: "La Réunion",
    code: "974",
    codeRegion: "04",
    timezone: "Indian/Reunion",
  },
  {
    label: "Mayotte",
    code: "976",
    codeRegion: "06",
    timezone: "Indian/Mayotte",
  },
];

export const upsertDepartments = async (prisma: PrismaClient) => {
  for (const department of departments) {
    await prisma.department.upsert({
      where: {
        code: department.code,
      },
      update: {
        timezone: department.timezone,
      },
      create: {
        code: department.code,
        label: department.label,
        timezone: department.timezone,
        region: {
          connect: {
            code: department.codeRegion,
          },
        },
        elligibleVAE: true,
      },
    });
  }
};
