type JuryResult =
  | "FULL_SUCCESS_OF_FULL_CERTIFICATION"
  | "FULL_SUCCESS_OF_PARTIAL_CERTIFICATION"
  | "PARTIAL_SUCCESS_OF_FULL_CERTIFICATION"
  | "PARTIAL_SUCCESS_OF_PARTIAL_CERTIFICATION"
  | "PARTIAL_SUCCESS_PENDING_CONFIRMATION"
  | "FAILURE"
  | "CANDIDATE_EXCUSED"
  | "CANDIDATE_ABSENT";

export interface JuryInfo {
  result: JuryResult;
  informationOfResult?: string;
}
