name: reva-admin-react

on:
  push:
    paths:
      - "packages/reva-admin-react/**"
      - "packages/reva-api/modules/**/*.graphql"
      - ".github/workflows/reva-admin-react.yml"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  NEXT_PUBLIC_WEBSITE_STRAPI_BASE_URL: "https://strapi.vae.gouv.fr"
  NEXT_PUBLIC_KEYCLOAK_REALM: "reva"
  # Should not be reachable, but we need to set a value and it won't work with https://auth.reva.incubateur.net
  NEXT_PUBLIC_KEYCLOAK_URL: "http://localhost:8888/auth"
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "reva-admin"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/reva-admin-react
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Admin node_modules cache
        id: admin-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ./packages/reva-admin-react/node_modules
          key: admin-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installing dependencies
        if: steps.admin-node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Running ESLint
        run: npm run lint

  cypress:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_KEYCLOAK_URL: "https://auth.reva.incubateur.net/"
    defaults:
      run:
        working-directory: ./packages/reva-admin-react
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Admin node_modules cache
        id: admin-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ./packages/reva-admin-react/node_modules
          key: admin-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installing dependencies
        if: steps.admin-node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Get Cypress version
        run: echo "CYPRESS_VERSION=`npm list | grep 'cypress'|sed 's/.*cypress@//'`" >> $GITHUB_ENV
      - name: Cypress Binaries cache
        id: cypress-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
          key: cypress-${{ env.CYPRESS_VERSION }}
      - name: Install Cypress binaries
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: npx cypress install
      - name: Build
        run: npm run build
      - name: Running Test
        run: NODE_ENV=production npm run test:ci

  playwright-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Admin node_modules cache
        id: admin-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ./packages/reva-admin-react/node_modules
          key: admin-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installing admin dependencies
        if: steps.admin-node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefix packages/reva-admin-react
      - name: API node_modules cache
        id: api-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ./packages/reva-api/node_modules
          key: api-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installing API dependencies
        if: steps.api-node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci --include=dev --prefix packages/reva-api
      - name: Generate GraphQL schema from API
        run: npm run graphql:generate --prefix packages/reva-api
      - name: Upload generated API schema
        uses: actions/upload-artifact@v4
        with:
          name: api-generated-schema
          path: packages/reva-api/modules/generated-graphql-schema.graphql
          retention-days: 1
      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=`npm list --prefix packages/reva-admin-react | grep '@playwright/test'|sed 's/.*playwright\/test@//'`" >> $GITHUB_ENV
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
        working-directory: ./packages/reva-admin-react

  playwright:
    timeout-minutes: 15
    needs: [playwright-setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    defaults:
      run:
        working-directory: ./packages/reva-admin-react
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Admin node_modules cache
        id: admin-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ./packages/reva-admin-react/node_modules
          key: admin-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installing dependencies
        if: steps.admin-node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=`npm list | grep '@playwright/test'|sed 's/.*playwright\/test@//'`" >> $GITHUB_ENV
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Install Chromium OS deps
        if: steps.cache-playwright.outputs.cache-hit == 'true'
        run: npx playwright install-deps chromium
      - name: Download generated API schema
        uses: actions/download-artifact@v4
        with:
          name: api-generated-schema
          path: packages/reva-api/modules/
      - name: Run Playwright tests
        run: npx playwright test --project=chromium --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-admin-${{ matrix.shardIndex }}
          path: packages/reva-admin-react/playwright-report/
          retention-days: 14
